### PR TITLE
Bugfix: speed showed sometimes 0.0 in UI.

### LINKED ISSUE #1117: Recording: speed shows 0.0 most of the time.
**Describe the bug**
When a track recording is on you can see that speed is 0.0 most of the time but average is computed and showed correctly.

Every once in a while you can see the current speed that vanishes quickly to show 0.0 again.

I've seen this issue using GPS speed (without speed sensor). I couldn't test it with speed sensor yet.

**To Reproduce**
1. Start a recording.
2. Look at speed.

**Technical information**
 - Device: Pixel 4a
 - OS: Android 12
 - OpenTracks version: debug version (current main branch).

### PR DESCRIPTION
**Pull request by dennisguse**
Fixes #1117.

Should only fix the problem for using the GPS.
BLE sensors might still be affected if they were - I had no time to check it.

### CODE REVIEW

**Comment by rgmf** [comment]
@dennisguse I tested it this morning driving to work and it doesn't work yet.

It's really strange because we can divide the (bad) behavior into two possibilities:
1. When I drove below a certain speed (let's say 40km/h) I saw how speed jumb between 0.0 and the current speed.
2. When I drove above a certain speed (more than 40km/h) I only saw 0.0 as speed.

I unknown the speed threshold for these two behaviors and I cannot understand such a odd behavior.

**Comment by dennisguse** [comment]
I guess it is GPS precision - the faster you go the less precise the measurements and thus less measurements might be reported by the GPS as well as ignored by OpenTracks due the accuracy.

Let me think about it ;)
PS elevation should also be affected.

**Comment by rgmf** [comment]
> PS elevation should also be affected.

I didn't realize.

**Comment by dennisguse** [comment]
@rgmf Now it should be working ;)
I am not a big fan of the solution, but it hopefully gets the job done :D

**Comment by rgmf** [comment]
@dennisguse if it works then it's enough for now. Anyway, there's room for improvements.

Installing... and I'll test it driving back to home.

**Comment by rgmf** [comment]
@dennisguse it worked like a charm using GPS speed.

**Review by rgmf — APPROVED** [review]

**Pull request merged**
