### PR TITLE
ViewPager2 migration and swipping between tabs fixed.

### PR DESCRIPTION
**Pull request by rgmf**
**Describe the pull request**
ViewPager2 migration and swipping between tabs fixed.

With zoom on charts you move chart and when you arrive to edge then move between tabs.

**Link to the the issue**
#105 
#522 

**License agreement**
By opening this pull request, you are providing your contribution under the _Apache License 2.0_ (see [LICENSE.md](LICENSE.md)).

### CODE REVIEW

**Comment by dennisguse** [comment]
Whaaat? Have to try this tomorrow! :sunglasses:

**Comment by dennisguse** [comment]
This gesture stuff is hard.
When I try to zoom using a pinch gesture (center to left-and right), I trigger the viewpager.
If I try to zoom pinch (center top-and-bottom), I zoom in....

I guess swiping via the viewpager should not be done when two fingers touch the screen (rather zoom only mode).
I guess `detectorZoom` needs to be modified for this.

**Comment by rgmf** [comment]
@dennisguse second try...

**Comment by rgmf** [comment]
@dennisguse second try...

You were right, now the gesture on ChartView are like before these changes.

**Review by dennisguse — COMMENTED** [review]
Code looks great.
Not sure of the behavior yet; see #543.

**Comment by rgmf** [comment]
Done in #543

**Pull request closed without merging**
