### PR TITLE
Added new option in Preferred rate setting: By Default.

### PR DESCRIPTION
**Pull request by rgmf**
**Describe the pull request**
I've added a "By Default" option in Preferred rate Settings. I think is a better text than "Auto", but it can be easily changed.

In `TrackIconUtils` I have created a new int array with all categories that use speed by default (there are sports that use speed and the other ones use pace). Every time a developer creates a new Icon has to add to this array the new sport if it uses speed by default.

From outside it can be used `isSpeedIcon` public static method to see if a category (activity type) uses speed (true) or pace (false).

Also `isReportSpeed` static method in `PreferencesUtils.java` now need a second argument: the track's category (activity type).

Those are basically all changes done.

**Link to the the issue**
https://github.com/OpenTracksApp/OpenTracks/issues/151

**License agreement**
By opening this pull request, you are providing your contribution under the _Apache License 2.0_ (see [LICENSE.md](LICENSE.md)).

### CODE REVIEW

**Comment by dennisguse** [comment]
@rgmf Thanks, I will take a look next week - I want to finish some other stuff first :)

**Comment by dennisguse** [comment]
@pstorch @rgmf What do we do about this PR?
I am still not a big fan, but I could imagine it might be useful.
I must admit I have not tried - but what happens if I am recording something and then change the activity type.
Does this result in an immediate change of `StatsFragment`?

PS: @rgmf Still nice work :)

**Comment by rgmf** [comment]
> I must admit I have not tried - but what happens if I am recording something and then change the activity type.
> Does this result in an immediate change of StatsFragment?

If you change from cycling to running, for example, then rate is change from km/h to min/km.

> PS: @rgmf Still nice work :)

Thank you ;)

> I am still not a big fan, but I could imagine it might be useful.

If you have not convinced don't merge it. Don't worry, it's a simple change, think about it and let's see ;)

**Comment by pstorch** [comment]
I don't have an opinion on it. I only do one sport with always the same setting. But if it is useful for others, then yes.

**Comment by dennisguse** [comment]
@rgmf If you like it just merge it ;)

**Comment by rgmf** [comment]
Ok, for me yes :D

**Pull request closed without merging**
