### PR TITLE
Public API: allow setting track properties (name, category, description) on StartRecording)

### LINKED ISSUE #1282: Public API: Additional parameters for StartRecording
**Is your feature request related to a problem? Please describe.**
Not a problem - more a comfort thing. I'm heavily using tasker to automate things. E.g. I have widgets for starting and stopping a dogwalk which will start OpenTracks, tell homeassistant I'm out with the dogs and set the ringing and media volume of the phone to max. When using the StartRecording and StopRecording intents, there is no possibility to set e.g. the workout type.

**Describe the solution you'd like**
I would like to suggest additional parameters for the StartRecording intent e.g. to set the workout type. This way, one can have e.g. different tasker homescreen widgets or generally, other apps can do thing with OpenTracks with a little more granular control.
E.g. starting and stopping a biking workout when unlocking/locking the bluetooth bike lock.

**Describe alternatives you've considered**
The only alternative as of now is to go into OpenTracks and stop an API-started recording from there to get to the save screen and enter parameters.

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by dennisguse**
@sgofferj does this work for you?

Fixes #1282.

### CODE REVIEW

**Comment by sgofferj** [comment]
Checking...

**Comment by dennisguse** [comment]
@sgofferj only in the one build by GitHub. You can download it from the actions.
The Fdroid nightly is build using the main branch.

**Comment by sgofferj** [comment]
Found it. I'm not overly familiar with intents. I tried just adding TRACK_DESCRIPTION: dogwalk to the Tasker extra field, but OT didn't take it. I guess, it should be something like de.dennisguse.(.*).TRACK_DESCRIPTION? Could you advise, what exactly?

**Comment by dennisguse** [comment]
(facepalm).
You did everything right... the data was just not stored - I forgot that we need to do this in the OpenTracks code base.
Can you test the new build?

**Comment by sgofferj** [comment]
Can't make it work... OT starts recording but neither name nor category nor description extras are taken...

**Comment by sgofferj** [comment]
Screenshot_20220702-215145

**Comment by dennisguse** [comment]
Thanks for the feedback. Let me see what I can do.

**Comment by dennisguse** [comment]
Now at least I learned how to trigger this via the shell.
Problem was: the parameters were only used when `Automatic data transfer` was enabled.

```
adb shell am start -n "de.dennisguse.opentracks.debug/de.dennisguse.opentracks.publicapi.StartRecording" --es "TRACK_NAME Test"
```

**Comment by sgofferj** [comment]
And now it works perfectly with tasker!

**Comment by dennisguse** [comment]
@sgofferj thanks for testing it - in some cases that is the hardest thing to do ;)

**Comment by sgofferj** [comment]
Thanks for implementing it!!!

**Pull request merged**
