### PR TITLE
Refactor#1118

### PR DESCRIPTION
**Pull request by dennisguse**
Some refactoring to enable #1118.

- [x] ~move toCSV and fromCSV for DataField into one place~
- [x] ~Remove Parceable from Layout and DataField~: used by:         `intent.putExtra(SettingsCustomLayoutEditActivity.EXTRA_LAYOUT, layout);`

- [x] move data extraction from StatisticsDataBuilder into StatisticData (use subclasses)
- [x] make to be inflated layout depending on DataField
- [x] ~use reflection to create new ViewHolder (`HashMap<DataFieldKey, class>`?)~ use a Map with Lambda for construction
- [x] Settings: figure out how to get the title (again)
- [x] rename Layout to `OpenTracksLayout/StatisticsLayout` RecordingLayout (or whatever)
- [x] ~StatisticsRecordingFragment: re-add divider (HorizontalLineStyle)~ not yet done; kind of complicated
- [x] ~StatisticsRecordedFragment: re-add sensor data~ (moved to #1426)

### CODE REVIEW

**Comment by dennisguse** [comment]
@rgmf quick question: why did you chose to use a RecyclerView for the StatisticsUI?
Somehow it feels like adding a lot of complexity just for rendering up to 10 views. 

And I am currently thinking is towards introducing separate layouts: one generic, one for clock, one for coordinates, one for BLE sensors (add battery level).
For data presentation, I was thinking about subclasses and thus separating the large if-block.

**Comment by rgmf** [comment]
> @rgmf quick question: why did you chose to use a RecyclerView for the StatisticsUI? Somehow it feels like adding a lot of complexity just for rendering up to 10 views.
> 

Well, I usually use RecyclerView for lists. It seems easy to me though there are a lot of complexity like you say.

> And I am currently thinking is towards introducing separate layouts: one generic, one for clock, one for coordinates, one for BLE  sensors (add battery level).
> For data presentation, I was thinking about subclasses and thus separating the large if-block.

That sounds like a good idea.

**Comment by dennisguse** [comment]
@rgmf thanks :)

**Comment by dennisguse** [comment]
@rgmf Another question: why did you compute the statistics for the UI in  a separate thread (in StatisticsDataModel)?

**Comment by rgmf** [comment]
> @rgmf Another question: why did you compute the statistics for the UI in a separate thread (in StatisticsDataModel)?

Because I've always made database operations in a separate thread. I guess there are db operations because I'm in the phone now. Tomorry I'll check the code out.

**Comment by dennisguse** [comment]
Took forever, but it is not even feature identical.

@rgmf @pstorch I really love working with all this frontend things, so this tooook way too long and was not that much fun.
Anyhow: we have now the ability to use a separate layout per DataField, so we can implement things like #1118 (e.g., presenting the current heart rate zone using some fancy UI) or #24.
For the UI I dropped the RecyclerView as it was adding too much complexity (we might re-add it later).

Anyhow: feedback appreciated.

**Pull request merged**
