### PR TITLE
Rough draft for export all tracks into one file

### PR DESCRIPTION
**Pull request by dennisguse**
I created a rough draft to export all tracks into one file.

TODO:
- [x] GPX/KML/KMZ can export multiple tracks into one file (was already done)
- [x] add setting to export into one file
- [x] send export task to ExportService
- [x] ExportService actually exports

@rgmf I was looking through the ExportService (and the communcation with it) and I am not sure how to do this.
Any suggestions?

### CODE REVIEW

**Comment by dennisguse** [comment]
@rgmf if you have some, it would be great if you could take a look at this.
Took me quite a while to figure out how to do this - and it is not yet the best solution.
... but it works :D

**Comment by pstorch** [comment]
I would like to test it, but can currently not switch to AS beta.

**Comment by dennisguse** [comment]
@pstorch the build should also work with AGP 8.0.X - the only thing that will be missing is Android 13's app-specific language selector.

**Comment by pstorch** [comment]
I exported > 100 tracks. File created without error. 
Looking for a tool which is capable to import and show the tracks. :wink:

A small issue: it reports that only 1 track was exported.

Screenshot_20230528_182643_OpenTracks

**Comment by pstorch** [comment]
Maybe it's not a good idea to visualize it in another tool. As this is meant for backup. So I deleted all tracks and tried to import again. But got this error:
Screenshot_20230528_190629_OpenTracks

**Comment by dennisguse** [comment]
@pstorch Amazing!
First: You found a bug in the KML exporter not creating valid XML for multiple tracks (this must  be ancient).
Second: for some mime types Android adds file suffixes (KML is one, but not GPX) :sunglasses: 
Translations for english updated.

The UI still lacks quite a lot, but it works - so our users will have to live with it aka MVP-style.

**Comment by pstorch** [comment]
Now it works. I see minimal differences in the overall statistic after reimport the big backup file. With this amount of files it might be negligible. 

As you said, the UI can be improved afterwards. It would help for example if the import counts the imported tracks to see some progress.

**Comment by dennisguse** [comment]
@pstorch thanks!!!

**Pull request merged**
