### PR TITLE
Intervals rate and gain

### PR DESCRIPTION
**Pull request by rgmf**
**Describe the pull request**
Intervals show distance, speed/pace (depending on user's settings) and gain.

I would like to test it in real activities (I hope next week) to move this Draft to PR.

**Motivation**
Speed or pace doesn't mean too much without gain. For example, an average speed of 10km/h by bike in an interval of 1km can seem too little but if you has a gain of 80m then 10km/h is so good.

That's why I think is necessary the gain in intervals.

PS/ When we add elevation loss to the logic of OpenTracks then we'll been able to add the elevation lost too.

**Link to the the issue**
(If available): The link to the issue that this pull request solves.

**License agreement**
By opening this pull request, you are providing your contribution under the _Apache License 2.0_ (see [LICENSE.md](LICENSE.md)).

**Note: new dependencies/libraries**
Please refrain from introducing new libraries without consulting the team.

### CODE REVIEW

**Comment by rgmf** [comment]
I've been using this for two weeks and it works fine. I think the code will be improved using TrackDataHub or ViewModel (pending in a next PR).

So, ready for merging, although it would be great if you could use it firstly.

**Comment by rgmf** [comment]
TrackDataHub instead of ContentProvider added to this PR.

Ready for merging. Squash also with the two main commits:
- Added gain to intervals.
- TrackDataHub instead of ContentProvider (code simplified).

**Comment by dennisguse** [comment]
@rgmf Do you still need a review?
If yes: I can take care of this tomorrow :)

**Comment by rgmf** [comment]
@dennisguse it's not necessary, the PR is ready to merge. I'll check it out the last time tomorrow and I'll merge it onto the main.

**Comment by dennisguse** [comment]
@rgmf Works for me ><

**Pull request merged**
