### PR TITLE
GPX: export heartrate, cadence, and speed via TrackPointExtension/v2

### LINKED ISSUE #181: GPX: export and import heartrate data
Hello,

OpenTracks was initaly my prefered app to monitor and record Heart Rate when biking.
But I have not been able to export hr data and import them in MyTourBook for example.

If I use AAT for recording, I can then export a .gpx file containing HR data and import it in MyTourBook.
But if I export .gpx from OpenTracks, I get no HR data in the file.
And if I export a .kmz / .kml file frome OpenTracks , I get a list of HR data at the end of the file, but I can't figure out how they can be related to time or position and I found no software able to read theses HR data (only geo data).

Would there be a solution to export HR data towards other software, ideally through a .gpx file like AAT or RunnerUp do?

Thanks a lot for your work and attention !

### PR DESCRIPTION
**Pull request by dennisguse**
This is a breaking change as speed exported with v3.7.6 cannot be imported.

Fixes #181.
Follow-up to #336.

@ronajon i fixed some smaller things (added missing members to AbstractFileImporter, enabled the tests, and changed speed to also use TrackPointExtension/v2.)
Well prepared :+1: 
It was just easier for to create a branch in the main repo...

### CODE REVIEW

**Comment by dennisguse** [comment]
@jensMF could you test this?
Does this solve your issue?

**Comment by jensMF** [comment]
> @jensMF could you test this?
> Does this solve your issue?

It nearly resolves the issue, thank you!
The only thing now is, the extensions have to be the last entry in their section.

So in the `<trkpt>` section time is the last entry at the moment and that gives errors when trying to validate:
```
SAXCount -v=always -n -s -f 2020-07-23\ 00:58.gpx

Error at file 2020-07-23 00:58.gpx, line 30, char 9
  Message: element 'time' is not allowed for content model '(ele?,time?,magvar?,geoidheight?,name?,cmt?,desc?,src?,link*,sym?,type?,fix?,sat?,hdop?,vdop?,pdop?,ageofdgpsdata?,dgpsid?,extensions?)'

Error at file 2020-07-23 00:58.gpx, line 37, char 9
  Message: element 'time' is not allowed for content model '(ele?,time?,magvar?,geoidheight?,name?,cmt?,desc?,src?,link*,sym?,type?,fix?,sat?,hdop?,vdop?,pdop?,ageofdgpsdata?,dgpsid?,extensions?)'

Error at file 2020-07-23 00:58.gpx, line 44, char 9
  Message: element 'time' is not allowed for content model '(ele?,time?,magvar?,geoidheight?,name?,cmt?,desc?,src?,link*,sym?,type?,fix?,sat?,hdop?,vdop?,pdop?,ageofdgpsdata?,dgpsid?,extensions?)'

Error at file 2020-07-23 00:58.gpx, line 51, char 9
  Message: element 'time' is not allowed for content model '(ele?,time?,magvar?,geoidheight?,name?,cmt?,desc?,src?,link*,sym?,type?,fix?,sat?,hdop?,vdop?,pdop?,ageofdgpsdata?,dgpsid?,extensions?)'

Error at file 2020-07-23 00:58.gpx, line 58, char 9
  Message: element 'time' is not allowed for content model '(ele?,time?,magvar?,geoidheight?,name?,cmt?,desc?,src?,link*,sym?,type?,fix?,sat?,hdop?,vdop?,pdop?,ageofdgpsdata?,dgpsid?,extensions?)'

Error at file 2020-07-23 00:58.gpx, line 65, char 9
  Message: element 'time' is not allowed for content model '(ele?,time?,magvar?,geoidheight?,name?,cmt?,desc?,src?,link*,sym?,type?,fix?,sat?,hdop?,vdop?,pdop?,ageofdgpsdata?,dgpsid?,extensions?)'

Error at file 2020-07-23 00:58.gpx, line 72, char 9
  Message: element 'time' is not allowed for content model '(ele?,time?,magvar?,geoidheight?,name?,cmt?,desc?,src?,link*,sym?,type?,fix?,sat?,hdop?,vdop?,pdop?,ageofdgpsdata?,dgpsid?,extensions?)'

Error at file 2020-07-23 00:58.gpx, line 79, char 9
  Message: element 'time' is not allowed for content model '(ele?,time?,magvar?,geoidheight?,name?,cmt?,desc?,src?,link*,sym?,type?,fix?,sat?,hdop?,vdop?,pdop?,ageofdgpsdata?,dgpsid?,extensions?)'

Error at file 2020-07-23 00:58.gpx, line 86, char 9
  Message: element 'time' is not allowed for content model '(ele?,time?,magvar?,geoidheight?,name?,cmt?,desc?,src?,link*,sym?,type?,fix?,sat?,hdop?,vdop?,pdop?,ageofdgpsdata?,dgpsid?,extensions?)'
```
SAXcount is part of Xerces: [https://de.wikipedia.org/wiki/Xerces](url)

**Comment by dennisguse** [comment]
@jensMF Thanks for testing!
And the info on how to actually test ;)

@ronajon Is it okay for you if I squash the commits into one before merging them into master?

**Comment by dennisguse** [comment]
What an effort to squash commits while keeping the original authorship.
I did it locally (and rephrased the @ronajon commits messages).
Github's UI would change the authorship (which is not correct).

Anyhow, it is done now :)

**Pull request merged**
