### PR TITLE
Setting to toggle distance/speed unit announcements

### LINKED ISSUE #1805: do not report units in the announcer
**Is your feature request related to a problem? Please describe.**
My problem is that the announcer talk can be talking for too long and "hiding" too much of a show I'm listening in the background while training.

**Describe the solution you'd like**
Do not report the units. They are useless. Sometimes they are too long like e.g. "kilometres per second". They are always the same as set in the settings.

Continue to report the name of the quantity being reported, eg. "Average speed" (or only "Speed" for interval speed average) and the number. The name needs to stay so that we do not need to remember the meaning of reported numbers by their ordinal position. It also allows me to increase concentration to catch the following number.

**Describe alternatives you've considered**
Unit reporting can be an option in the settings but I think it is not worth it.

### PR DESCRIPTION
**Pull request by dm1cael**
**Describe the pull request**
This pull request should fix #1805, while creating the option to enable or disable this type of announcement.

**Link to the the issue**
 #1805

**License agreement**
By opening this pull request, you are providing your contribution under the _Apache License 2.0_ (see [LICENSE.md](LICENSE.md)).

### CODE REVIEW

**Comment by dennisguse** [comment]
Looks good.
Did you check that the tests are green?

**Comment by dm1cael** [comment]
They are.
image

**Comment by dennisguse** [comment]
I need to fix #1898 first and then merge your PR - somewhen next week :D

i guess you are fixing #1805, right?
If so, can you add "Fixes #1805." as a 2nd line in the commit message (Github then connects the commit and the issue together).

**Comment by dm1cael** [comment]
Done. Good luck with #1898 :)

**Comment by dennisguse** [comment]
Looks good - will ship with the next release!
Thanks :D

**Pull request merged**
