### PR TITLE
Remove icon from bottombars.

### PR DESCRIPTION
**Pull request by dennisguse**
Saves screen space and (hopefully) less complaints from PlayStore.

Part of #1329.

TL;DR

I am still "working" with the Google people to get accept a new version of OpenTracks.

### CODE REVIEW

**Comment by pstorch** [comment]
The version with the new gradle build tools doesn't work on my system. But I could build and run it when reverting it.
So yes, icons are gone from the bottom bar and the about dialog.

**Comment by dennisguse** [comment]
I am confused  about this whole desugar thing.

I am running AndroidStudios Beta in parallel as I always hope they fixed some bugs...


PS does the whole icon removal make sense?

**Comment by pstorch** [comment]
> PS does the whole icon removal make sense?

It is not as pretty as with icon, but if the icon is the problem, then ...

**Review by rgmf — APPROVED** [review]
It's strange for me because It got used to seeing it, but It's good for me.

**Comment by dennisguse** [comment]
Felt the same for me.
For now v4.0.6 got accepted; let's build a solution if need it next time ;)

**Pull request closed without merging**
