### PR TITLE
Import/Export GPS accuracy ot GPX/KML

### PR DESCRIPTION
**Pull request by dennisguse**
Follow-up to #1182.

@brianjmurrell Does this work for you?

### CODE REVIEW

**Comment by brianjmurrell** [comment]
@dennisguse Awesome!  You beat me to it.  I was interior house painting this weekend so no time for hacking.

I have merged this into my branch and will give it a go on my next outdoor walk.

Am I correct to understand from the patch that if GPS is disabled for a track, there will be no `accuracy_horizontal` with the trackpoints in the GPX file?  If so, I can also confirm that on my next treadmill activity.

**Comment by dennisguse** [comment]
@brianjmurrell No worries.
If  no GPS is used, there will be no TrackPoints exported to GPX.
Here, we only include TrackPoints that were provided by GPS (i.e., have latitude/longitude) as this is mandatory for GPX (to the best of my knowledge) - so this cannot happen.
For sensor data: we aggregate it (for distance summing it up) and add it to the next TrackPoint was provided by GPS.

For KML, coordinates are optional, but most tools interpret missing coordinates as lat=0,lng=0.
Here, we deployed some fixes for open-source apps - some details can be found in #639.

If you want to export non-GPS data, you need to use KML or we need to figure out how to do this with GPX or we implement #999.
That's why I implement it, so you can could use KML :D

**Comment by brianjmurrell** [comment]
But I get GPX files with plenty of points in them even when I have the GPS icon on the top bar toggled off.

Is https://github.com/pytrainer/pytrainer/blob/1ebddea436117fec35abff6d0cf060bc290e5a04/schemas/Cluetrust_gpxdata10.xsd#L46-L48 for "trackpoints" with no coordinates?

**Comment by dennisguse** [comment]
@brianjmurrell Can you check what TrackPoints are exported and if they confirm if they contain coordinates or not?

And regarding Cluetrust... jupp - but I can really recommend KML (because that is already implemented) :D

**Comment by brianjmurrell** [comment]
> @brianjmurrell Can you check what TrackPoints are exported and if they confirm if they contain coordinates or not?

Yes they do.  The same (for all intents and purposes) `lat` and `lon` on every one of them.

> And regarding Cluetrust... jupp - but I can really recommend KML (because that is already implemented) :D

Implemented on OpenTracks' end.  My app was written to import GPX.  :frowning:

**Comment by dennisguse** [comment]
Are those coordinates valid?
I mean that should not be the case if the GPS is disabled or the phone was used indoor.
Interesting but weird - I will check this tomorrow with my phone. Hopefully, there is no ugly bug.

About GPX: which parser did you use? I guess you can also just use the KMLTrackImporter from OpenTracks (it's Apache 2.0) and replace your current implementation. No need to reimplements a parser and it should not be too complicated.

Extending GPX might not be straight forward and makes parsing it even more complex.

**Comment by brianjmurrell** [comment]
> Are those coordinates valid?

They are, indeed!  Opening that GPX file with gnome-maps takes me right to where that activity was going on.

> I mean that should not be the case if the GPS is disabled or the phone was used indoor. 

Indeed.

> About GPX: which parser did you use?

I am using Python and pygpx.  I suppose there is probably a KML reader as well that I (hope) I can substitute in easily enough.

**Comment by dennisguse** [comment]
@brianjmurrell before you do this: let me implement #999.
And reading CSV should be piece cake - no point in creating a parser to KML and all it's "features" (aka the custom data arrays).
The CSV export would only include the TrackPoints - no statistics; and very look like our TrackPoint table.

**Comment by brianjmurrell** [comment]
> creating a parser to KML

Oh, I am fairly sure I don't have to do that.  I would be very surprised if there were not already a python library for doing it.  So hopefully it operates similarly to the python GPX parser.

**Comment by brianjmurrell** [comment]
> > Are those coordinates valid?
> 
> They are, indeed! Opening that GPX file with gnome-maps takes me right to where that activity was going on.

Any thoughts on this location privacy leak?

**Comment by dennisguse** [comment]
@brianjmurrell depends.
Was the location permission granted?
Was the GPS disabled on the device while recording?

OpenTracks has no functionality to disable/ignore GPS for a specific recording (yet).
And if the OS is providing this data, it will just store it.

**Comment by brianjmurrell** [comment]
> Was the location permission granted?

For the app or the track?  For the app, of course.  I use it both indoors and out.

> Was the GPS disabled on the device while recording?

Yes.
 
> OpenTracks has no functionality to disable/ignore GPS for a specific recording (yet). And if the OS is providing this data, it will just store it.

Oh.  What does the location toggle at the top of the screen where you press start to start a track do then?

I guess I am back to my original suggestion of a data item in a track whether that toggle was on or off for the track if it's not actually disabling the tracking of GPS.

Ultimately reading a track I want to know if the GPS data is meaningful (i.e. I was outdoors walking) or I should disregard it as it was all in the same location as I was on a treadmill.

I suppose I could derive the latter simply by measuring GPS-calculated distance of the track (compared to sensor distance which is used in preference to GPS distance in the GPX entries as I understand it) and if it's below some threshold assume the user was on a treadmill (or jogging in place, etc. :smile:).

**Comment by dennisguse** [comment]
The location toggle on TrackListActivity can be used to pre-start the sensors (e.g., that the GPS already can acquire fix) before starting the actual recording. We might need to change this, but that was the original purpose ;)
So, if you don't want GPS, you need to disable via the Android system.

There is quite some potential to overhaul part of the UI, but that is never as easy as it sounds...

And yes: if you want to figure out if something was indoors that might be an option.
You can also check how many TrackPoints actually have a location.

PS/ are you using KML or CSV now?
PPS/ CSV cannot be imported, so not useful for backups.

**Pull request merged**
