### PR TITLE
Chart fragment#696

### PR DESCRIPTION
**Pull request by dennisguse**
While checking for #696, I saw some interesting things:
* ChartFragment now uses XML-based layout (without a useless LinearLayout)
* ChartFragment always accepts data from TrackDataHub (also while being paused) to be always up to date
  (should not happen as we pause/resume the TrackDataHub).

Basically, just simplifying.

### CODE REVIEW

**Review by rgmf — COMMENTED** [review]
I get the following crash when I'm watching the chart and I change from OT to another app and back to OT:

```log
2021-05-22 20:14:41.060 4558-4680/de.dennisguse.opentracks.debug E/AndroidRuntime: FATAL EXCEPTION: TrackDataHub
    Process: de.dennisguse.opentracks.debug, PID: 4558
    java.lang.NullPointerException: Attempt to invoke virtual method 'void de.dennisguse.opentracks.stats.TrackStatisticsUpdater.addTrackPoint(de.dennisguse.opentracks.content.data.TrackPoint, de.dennisguse.opentracks.content.data.Distance)' on a null object reference
        at de.dennisguse.opentracks.content.TrackDataHub.notifyTrackPointsTableUpdate(TrackDataHub.java:378)
        at de.dennisguse.opentracks.content.TrackDataHub.loadDataForListener(TrackDataHub.java:261)
        at de.dennisguse.opentracks.content.TrackDataHub.lambda$registerTrackDataListener$1$TrackDataHub(TrackDataHub.java:194)
        at de.dennisguse.opentracks.content.-$$Lambda$TrackDataHub$mbEXkhjouip_-npcoIfM1Jx00V4.run(Unknown Source:12)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

More details:
- Android Studio show several warnings on ChartFragment.
- I only can reproduce the error on long tracks (4h track for 30min track, for instance).
- If the first time you change between apps you don't get this error, then try to change between apps once again until you get the error: sometimes you get the error the first time and other times you get the error in the second, third... time.

I've tried to attach a video but I can't. I send you it by e-mail.

**Comment by rgmf** [comment]
@dennisguse I've just stumbled upon other error:

```log
2021-05-22 21:05:22.700 21034-21069/de.dennisguse.opentracks.debug E/AndroidRuntime: FATAL EXCEPTION: TrackDataHub
    Process: de.dennisguse.opentracks.debug, PID: 21034
    java.lang.NullPointerException: Attempt to read from field 'de.dennisguse.opentracks.chart.ChartView de.dennisguse.opentracks.databinding.ChartBinding.chartView' on a null object reference
        at de.dennisguse.opentracks.fragments.ChartFragment.onSampledInTrackPoint(ChartFragment.java:197)
        at de.dennisguse.opentracks.content.TrackDataHub.notifyTrackPointsTableUpdate(TrackDataHub.java:388)
        at de.dennisguse.opentracks.content.TrackDataHub.loadDataForListener(TrackDataHub.java:261)
        at de.dennisguse.opentracks.content.TrackDataHub.lambda$registerTrackDataListener$1$TrackDataHub(TrackDataHub.java:194)
        at de.dennisguse.opentracks.content.-$$Lambda$TrackDataHub$mbEXkhjouip_-npcoIfM1Jx00V4.run(Unknown Source:12)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by dennisguse** [comment]
@rgmf Regarding the first problem: :facepalm: -> that is #787.
I forgot to rebase these changes onto main after fixing #787.

About the second: let me take a look!
Thanks for finding it!

PS: I will just release v3.18.2 to incl. #787.

**Comment by rgmf** [comment]
@dennisguse so that's great if it's already fixed :tada: 
:rofl: :rofl:

**Review by rgmf — APPROVED** [review]
Looks like all work well. I can't reproduce the last error anymore (maybe with isResume check it's fixed).

**Pull request merged**
