### PR TITLE
Gps permission#1061

### PR DESCRIPTION
**Pull request by dennisguse**
... as we almost have a snackbar: we can make GPS optional :)

### CODE REVIEW

**Comment by rgmf** [comment]
l've started to test it from Virtual Device (API24) and it didn't work as OT didn't ask me for permission.

Also, when I stopped the activity I got the following crash:

```log
2022-01-31 19:56:22.807 4635-4635/de.dennisguse.opentracks.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.dennisguse.opentracks.debug, PID: 4635
    java.lang.RuntimeException: Unable to stop service de.dennisguse.opentracks.services.TrackRecordingService@dc8a1d6: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Context.checkPermission(java.lang.String, int, int)' on a null object reference
        at android.app.ActivityThread.handleStopService(ActivityThread.java:3344)
        at android.app.ActivityThread.-wrap27(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1570)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Context.checkPermission(java.lang.String, int, int)' on a null object reference
        at androidx.core.content.ContextCompat.checkSelfPermission(ContextCompat.java:555)
        at de.dennisguse.opentracks.util.PermissionUtils.hasGPSPermission(PermissionUtils.java:15)
        at de.dennisguse.opentracks.services.handlers.GPSHandler.onStop(GPSHandler.java:57)
        at de.dennisguse.opentracks.services.handlers.TrackPointCreator.stop(TrackPointCreator.java:96)
        at de.dennisguse.opentracks.services.TrackRecordingService.onDestroy(TrackRecordingService.java:130)
        at android.app.ActivityThread.handleStopService(ActivityThread.java:3327)
        at android.app.ActivityThread.-wrap27(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1570) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
```

PS/ The same for API30.

**Comment by dennisguse** [comment]
@rgmf Valid point; will force push the fix!

**Comment by dennisguse** [comment]
@rgmf Can you give this another spin?

**Comment by rgmf** [comment]
I still get the same error :(

**Comment by dennisguse** [comment]
@rgmf Would you have time to test it again?

**Comment by rgmf** [comment]
@dennisguse it doesn't crash anymore but it never ask me for GPS permission.

Would it ask me for GPS permission if I start a recording with GPS on?

**Comment by dennisguse** [comment]
@rgmf ... while cleaning up, I was accidentally inverting the check if the permission was already granted...
Fixed now.
Again thanks for testing...

**Pull request merged**
