### PR TITLE
for #1025 exportdir failed to create document

### PR DESCRIPTION
**Pull request by pstorch**
I found a few things to tackle the export to Nextcloud error.

One thing was that Nextclound can't handle `:` character in filename, so I need to strip them from the trackname before creating the file.

Then I found a few things with the flags and handling of cases where the directory uri might not be writable.

This is just a quick hack, not tested well. Please feel free to have a look anyway.

### CODE REVIEW

**Comment by dennisguse** [comment]
Can we somehow make get it in a way to also fix this?
 https://github.com/OpenTracksApp/OpenTracks/issues/254

**Comment by pstorch** [comment]
I think it fixes that, too.

**Comment by dennisguse** [comment]
... but not for the sharing functionality, right?

**Comment by rgmf** [comment]
@pstorch this fixes the issue I had with a track of mine :tada:

**Comment by pstorch** [comment]
I've updated the PR to use the `FileUtils.sanitizeFileName` for the Export and also for the Share function to fix #254

**Review by dennisguse — APPROVED** [review]
Looks pretty good!

**Comment by pstorch** [comment]
Then let's test it in the Nightlies 😉

**Comment by dennisguse** [comment]
@pstorch ... just updated :D

**Comment by pstorch** [comment]
That's the build from last night. This change is not in yet.

**Comment by pstorch** [comment]
Or did you use the build from the GitHub action?

**Comment by dennisguse** [comment]
@pstorch Nope, you I your nightly builds.
But I am also not a test user for this as I don't sync my tracks :man_shrugging:

**Pull request merged**
