### PR TITLE
Refactor exporter

### PR DESCRIPTION
**Pull request by thrillfall**
exporter refactoring as foundation to https://github.com/OpenTracksApp/OpenTracks/pull/378

### CODE REVIEW

**Comment by dennisguse** [comment]
Looks good - just one unused variable.
But I don't have write access to your fork, so here is the patch :)
```
From a9ec7b6313d612ab118172fd6df0814109d556ea Mon Sep 17 00:00:00 2001
From: Dennis Guse <dennis.guse@alumni.tu-berlin.de>
Date: Sun, 16 Aug 2020 21:10:01 +0200
Subject: [PATCH] Removed unused variable.

---
 .../content/provider/ShareContentProvider.java       |  3 +--
 .../opentracks/io/file/TrackFileFormat.java          | 12 ++++--------
 2 files changed, 5 insertions(+), 10 deletions(-)

diff --git a/src/main/java/de/dennisguse/opentracks/content/provider/ShareContentProvider.java b/src/main/java/de/dennisguse/opentracks/content/provider/ShareContentProvider.java
index 57970cd9..42a08b07 100644
--- a/src/main/java/de/dennisguse/opentracks/content/provider/ShareContentProvider.java
+++ b/src/main/java/de/dennisguse/opentracks/content/provider/ShareContentProvider.java
@@ -208,8 +208,7 @@ public class ShareContentProvider extends CustomContentProvider implements ICont
             tracks[i] = contentProviderUtils.getTrack(trackIds[i]);
         }
 
-        boolean hasMultipleTracks = tracks.length > 1;
-        final TrackExporter trackExporter = getTrackFileFormat(uri).newTrackExporter(getContext(), hasMultipleTracks);
+        final TrackExporter trackExporter = getTrackFileFormat(uri).newTrackExporter(getContext());
 
         PipeDataWriter<String> pipeDataWriter = (output, uri1, mimeType, opts, args) -> {
             try (FileOutputStream fileOutputStream = new FileOutputStream(output.getFileDescriptor())) {
diff --git a/src/main/java/de/dennisguse/opentracks/io/file/TrackFileFormat.java b/src/main/java/de/dennisguse/opentracks/io/file/TrackFileFormat.java
index 99d51a46..09a17da8 100644
--- a/src/main/java/de/dennisguse/opentracks/io/file/TrackFileFormat.java
+++ b/src/main/java/de/dennisguse/opentracks/io/file/TrackFileFormat.java
@@ -72,7 +72,7 @@ public enum TrackFileFormat {
             return new KmlTrackWriter(context, false, false, exportPhotos);
         }
 
-        public TrackExporter newTrackExporter(Context context, boolean hasMultipleTracks) {
+        public TrackExporter newTrackExporter(Context context) {
             return newKmzTrackExporter(context, this.newTrackWriter(context), exportPhotos);
         }
 
@@ -99,7 +99,7 @@ public enum TrackFileFormat {
             return new KmlTrackWriter(context, true, false, exportPhotos);
         }
 
-        public TrackExporter newTrackExporter(Context context, boolean hasMultipleTracks) {
+        public TrackExporter newTrackExporter(Context context) {
             return newKmzTrackExporter(context, this.newTrackWriter(context), exportPhotos);
         }
 
@@ -132,7 +132,7 @@ public enum TrackFileFormat {
             return MIME_KMZ;
         }
 
-        public TrackExporter newTrackExporter(Context context, boolean hasMultipleTracks) {
+        public TrackExporter newTrackExporter(Context context) {
             return newKmzTrackExporter(context, this.newTrackWriter(context), exportPhotos);
         }
 
@@ -161,7 +161,7 @@ public enum TrackFileFormat {
             return MIME_KMZ;
         }
 
-        public TrackExporter newTrackExporter(Context context, boolean hasMultipleTracks) {
+        public TrackExporter newTrackExporter(Context context) {
             return newKmzTrackExporter(context, newTrackWriter(context), exportPhotos);
         }
 
@@ -209,10 +209,6 @@ public enum TrackFileFormat {
     public abstract String getMimeType();
 
     public TrackExporter newTrackExporter(Context context) {
-        return newTrackExporter(context, false);
-    }
-
-    public TrackExporter newTrackExporter(Context context, boolean hasMultipleTracks) {
         ContentProviderUtils contentProviderUtils = new ContentProviderUtils(context);
         TrackWriter trackWriter = newTrackWriter(context);
         return new FileTrackExporter(contentProviderUtils, trackWriter);
-- 
2.20.1
```

**Comment by thrillfall** [comment]
Thanks. I applied you patch. I obviously lost track of refactoring out the dependency to that flag from the exporter.

**Comment by dennisguse** [comment]
....(if I do via Github, the authorship is changed)....

**Comment by thrillfall** [comment]
> @thrillfall nice work!
> Can you rebase and squash the commits?

i rebased and squashed the last 2 commits (since they were really the same thing). As for the other commits i'd rather leave them as they are since everyone has a well written commit message explaining what has happend. Squashing all of this would rid us of the history of evolving code

**Comment by dennisguse** [comment]
Works for me.

**Pull request merged**
