### PR TITLE
Use distance from cycling speed sensors.

### PR DESCRIPTION
**Pull request by dennisguse**
For cycling, we already support wheel rotation (aka speed) sensors.
These can also be used to distance (actually easier than computing the speed).

This PR contains:
* [x] distance derive distance between two sensor measurements (like speed)
* [x] store distance in an extra column (sensor_distance)
* [x] adapt trackStatistics to either use sensor_distance or distance from previous trackpoint (old behavior)
* [x] export distance to KML/KMZ
* [x] (kind ugly) we need to store the distance between two  trackpoints somehow (SensorData only supports between two sensor measurements).
  Actually, we need some integration (e.g., averaging?) of sensor measurements as so far we only store the last provided value; see https://github.com/OpenTracksApp/OpenTracks/pull/592#issuecomment-775488089
* [x] check Garmin Speed 2
* [x] extend trackStatisticsUpdater
* [ ] do some actual testing

### CODE REVIEW

**Comment by dennisguse** [comment]
@ChristophWurst You can try this if you want (it should also work indoors).
The distance is reported between to sensor measurements, so it will be completely off - but it would be interesting if the rest is already working. I don't have any test equipment here - I "just" implemented it. ;)

I have not (yet) a good concept on how to gather the distance correctly, but it is not rocket science and we have another related issue with the other sensor data (we only store the last one, but we should do some averaging or so).
I guess enhancing SensorDataSet will be a good way...

**Comment by ChristophWurst** [comment]
> @ChristophWurst You can try this if you want (it should also work indoors).

Will test soonish :pray:

**Comment by dennisguse** [comment]
@ChristophWurst Implementation should be complete, but (due to lack of sensors) completely untested.
If you have some time to test it, it would be great.
Also works in an indoor situation (except that is only once stored at the end if no GPS signal is available).

PS: I, finally, ordered one today :sunglasses:

**Comment by dennisguse** [comment]
@ChristophWurst This is good to go (from my side) - would be great to see if it also works for you.

**Comment by ChristophWurst** [comment]
I put the Garmin Speed Sensor 2 onto my front wheel, connected it in the settings and gave it a manual spin.

The speed and distance is negative for me:

<details>

ot

</details>

Wheel spun backwards:

<details>

ot2

</details>

Summary:

<details>

ot3

</details>

**Comment by ChristophWurst** [comment]
The second screenshot is from running the wheel backwards. It always reported negative numbers. I don't think this sensor has a right or wrong direction.

**Comment by dennisguse** [comment]
@%#%#%&@ why can those sensor manufacturers not just build something according to the *standard*. Wahoo sends cadence as speed. Garmin sends cadence as speed. And Garmin sometimes counts backward. 

The hacky workaround is just to compute the absolute value of the wheel rotation difference.
But still.
Standards, right?

**Comment by dennisguse** [comment]
@ChristophWurst I added a workaround that hopefully works.
But can you check the firmware on your sensor?
I just found that you actually need other Garmin equipment to do this; seemingly the mobile cannot do this :man_shrugging: 
https://support.garmin.com/de-DE/?partNumber=010-12843-00&tab=software

**Comment by ChristophWurst** [comment]
Well, tried that. I'm generally trying to avoid any proprietary services with mandatory sign-up, hence I didn't have the Connect app before. In any case it fails pairing the sensor, while Android successfully lists it in the bluetooth settings. I can't tell what firmware I have. It must be the one that came with the device when I bought it.

**Comment by dennisguse** [comment]
@ChristophWurst Does the workaround work for you?
(I would like to merge this soonish as it blocks some refactoring in the importer code).

**Pull request merged**
