### PR TITLE
Remove Track.Id and Marker.Id.isValid()

### PR DESCRIPTION
**Pull request by dennisguse**
isValid() should not be necessary.
We can just use null as Track.Id or Marker.Id if the marker/track was not loaded from the database.

### CODE REVIEW

**Comment by dennisguse** [comment]
Merge _after_ v3.14.1 as this might break stuff.

**Comment by rgmf** [comment]
> Merge _after_ v3.14.1 as this might break stuff.

Good idea :D

I'm going to install this branch on my phone and use it. I'll inform you of any issue ;)

**Review by rgmf — APPROVED** [review]
I've not been got problems  for these days using this branch... Good for me.

**Comment by dennisguse** [comment]
@rgmf Great; I will just add some smaller (non-relevant) cleanups and merge it then.
I stumpled upon some mess in the tests while working on #316 and will put these in here.

**Pull request merged**
