### PR TITLE
Provide option to use network provider for location data

### PR DESCRIPTION
**Pull request by eiabea**
Listening on this setting to request location updates

# Thanks for your contribution.

**Describe the pull request**
I am using a Nexus 5X without any Google Play Services which results in no location data. The workaround i propose here is to let the user decide in the settings to use the inaccurate NETWORK_PROVIDER instead of the GPS_PROVIDER to be able to use the app even without Google Play Services

**Link to the the issue**
- No linked issue

**License agreement**
By opening this pull request, you are providing your contribution under the _Apache License 2.0_ (see [LICENSE.md](LICENSE.md)).

**Note: new dependencies/libraries**
- No new deps

### CODE REVIEW

**Comment by dennisguse** [comment]
I am not sure I understand why.
I am using two phones (no Google Play Services) and both work fine with GPS_PROVIDER.
What would be the advantage of allowing NETWORK_PROVIDER or what is the problem you want to solve?

PS: Code in itself looks good!

**Comment by eiabea** [comment]
@dennisguse interesting, maybe i have an issue with my phone, i get following crash when using the GPS_PROVIDER

```
03-04 13:08:44.833 17558 17559 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 17559 (Loc_hal_worker), pid 17558 (gnss@1.0-servic)
03-04 13:08:44.883 18837 18837 E cutils-trace: Error opening trace file: No such file or directory (2)
03-04 13:08:44.898 18838 18838 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
03-04 13:08:44.901   667   667 I /system/bin/tombstoned: received crash request for pid 17559
03-04 13:08:44.903 18838 18838 I crash_dump64: performing dump of process 17558 (target tid = 17559)
03-04 13:08:44.907 18838 18838 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-04 13:08:44.907 18838 18838 F DEBUG   : LineageOS Version: '17.1-20200915-UNOFFICIAL-bullhead'
03-04 13:08:44.908 18838 18838 F DEBUG   : Build fingerprint: 'google/bullhead/bullhead:8.1.0/OPM7.181205.001/5080180:user/release-keys'
03-04 13:08:44.908 18838 18838 F DEBUG   : Revision: 'rev_1.0'
03-04 13:08:44.909 18838 18838 F DEBUG   : ABI: 'arm64'
03-04 13:08:44.912 18838 18838 F DEBUG   : Timestamp: 2021-03-04 13:08:44+0100
03-04 13:08:44.912 18838 18838 F DEBUG   : pid: 17558, tid: 17559, name: Loc_hal_worker  >>> /vendor/bin/hw/android.hardware.gnss@1.0-service <<<
03-04 13:08:44.913 18838 18838 F DEBUG   : uid: 1021
03-04 13:08:44.913 18838 18838 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
03-04 13:08:44.913 18838 18838 F DEBUG   : Abort message: 'Check failed: data[size] == '\0' '
03-04 13:08:44.914 18838 18838 F DEBUG   :     x0  0000000000000000  x1  0000000000004497  x2  0000000000000006  x3  0000007db2d91850
03-04 13:08:44.914 18838 18838 F DEBUG   :     x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  7f7f7f7f7f7f7f7f
03-04 13:08:44.915 18838 18838 F DEBUG   :     x8  00000000000000f0  x9  0000007db44584a0  x10 0000000000000000  x11 0000000000000001
03-04 13:08:44.915 18838 18838 F DEBUG   :     x12 0000007db3e64a0c  x13 ffffffffffffffff  x14 0000000000000004  x15 ffffffffffffffff
03-04 13:08:44.916 18838 18838 F DEBUG   :     x16 0000007db45258c0  x17 0000007db4503290  x18 0000007db2dd7000  x19 00000000000000ac
03-04 13:08:44.916 18838 18838 F DEBUG   :     x20 0000000000004496  x21 00000000000000b2  x22 0000000000004497  x23 00000000ffffffff
03-04 13:08:44.916 18838 18838 F DEBUG   :     x24 0000007db2d92020  x25 00000000000cab69  x26 0000000000000005  x27 0000007db2d91b40
03-04 13:08:44.917 18838 18838 F DEBUG   :     x28 0000007db36f8010  x29 0000007db2d91900
03-04 13:08:44.917 18838 18838 F DEBUG   :     sp  0000007db2d91830  lr  0000007db44b60f0  pc  0000007db44b6120
03-04 13:08:44.928 18838 18838 F DEBUG   : 
03-04 13:08:44.928 18838 18838 F DEBUG   : backtrace:
03-04 13:08:44.929 18838 18838 F DEBUG   :       #00 pc 0000000000082120  /apex/com.android.runtime/lib64/bionic/libc.so (abort+176) (BuildId: ec1a54aa20e1543c38467684c6b06dbf)
03-04 13:08:44.930 18838 18838 F DEBUG   :       #01 pc 000000000000bc3c  /system/lib64/libbase.so (android::base::DefaultAborter(char const*)+12) (BuildId: 107ca9d332172b9cb8027b953d0628e2)
03-04 13:08:44.930 18838 18838 F DEBUG   :       #02 pc 000000000000c650  /system/lib64/libbase.so (android::base::LogMessage::~LogMessage()+608) (BuildId: 107ca9d332172b9cb8027b953d0628e2)
03-04 13:08:44.931 18838 18838 F DEBUG   :       #03 pc 000000000005211c  /system/lib64/libhidlbase.so (android::hardware::hidl_string::setToExternal(char const*, unsigned long)+348) (BuildId: 66d22f07f8e5f5210b6d145f43eb600c)
03-04 13:08:44.931 18838 18838 F DEBUG   :       #04 pc 0000000000011994  /vendor/lib64/hw/android.hardware.gnss@1.0-impl.so (android::hardware::gnss::V1_0::implementation::Gnss::nmeaCb(long, char const*, int)+84) (BuildId: 25e3c04b2515208ed936f67007e277d9)
03-04 13:08:44.932 18838 18838 F DEBUG   :       #05 pc 00000000000178f4  /system/lib64/libloc_eng.so (loc_eng_nmea_send(char*, int, loc_eng_data_s*)+292) (BuildId: 39826243b9f80ea47f412ec40e26baa0)
03-04 13:08:44.932 18838 18838 F DEBUG   :       #06 pc 0000000000018b60  /system/lib64/libloc_eng.so (loc_eng_nmea_generate_sv(loc_eng_data_s*, GpsSvStatus const&, GpsLocationExtended const&)+800) (BuildId: 39826243b9f80ea47f412ec40e26baa0)
03-04 13:08:44.933 18838 18838 F DEBUG   :       #07 pc 0000000000006118  /system/lib64/libloc_core.so (loc_core::MsgTask::loopMain(void*)+128) (BuildId: d37da83b90cec1ab35b9385a8d638011)
03-04 13:08:44.933 18838 18838 F DEBUG   :       #08 pc 000000000001002c  /vendor/lib64/hw/android.hardware.gnss@1.0-impl.so (threadFunc(void*)+12) (BuildId: 25e3c04b2515208ed936f67007e277d9)
03-04 13:08:44.934 18838 18838 F DEBUG   :       #09 pc 00000000000e357c  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36) (BuildId: ec1a54aa20e1543c38467684c6b06dbf)
03-04 13:08:44.935 18838 18838 F DEBUG   :       #10 pc 0000000000083d18  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: ec1a54aa20e1543c38467684c6b06dbf)
```

**Comment by dennisguse** [comment]
That looks definitely not healthy.
Also the first time i have seen this.
Usually, everything "just works".
Might be related with the image that you are running...

**Comment by dennisguse** [comment]
@eiabea if we really need this, please re-open this PR.
I will close it for now.

**Pull request closed without merging**
