### PR TITLE
Fix aggregated stats don't show imperial units for avg pace

### LINKED ISSUE #1634: Aggregated stats shows km when user selects imperial units
Should display minutes per mile not min per kilometer 

**To Reproduce**
1. In settings set the preferred units to imperial
2. Set the preferred activity to running or street running and preferred rate to "pace (min/mi)"
3. Click on stats icon on lower left.

See screen shot.  

Oddly, if the activity type is "unknown" for all the aggregated workouts, the correct units are displayed

**Technical information**
 - Device: Google pix re on Android 13
 - OpenTracks version: 4.6.1
 
Screenshot_20230708-155351

### PR DESCRIPTION
**Pull request by khao-soi**
fixes #1634

### CODE REVIEW

**Review by dennisguse — APPROVED** [review]
Looks good. 

Only thing: can you add the "Fixes #1684." into the commit message (2nd line)? 
This way the commit gets linked to the issues; useful for future engineers ;)

**Comment by khao-soi** [comment]
Done. I screwed up with android studio and created a second commit instead of ammending it. Hope thats ok, otherwise I will create a new PR.

**Comment by dennisguse** [comment]
You can just squash the commits and then force push. No need to create a new PR ;)

**Comment by khao-soi** [comment]
Ehm, it says I can't because the inital commit has 2 parents.

**Comment by dennisguse** [comment]
You have to remove the merge commit and then it works.

PS on branches it is way easier to rebase + force push to get updates from the parent branch. 

Merging is usually complicating things :)

**Comment by khao-soi** [comment]
Yeah, I wanted to rebase like usual via CLI but somehow I thought it'd be a good idea to deal with it via Android Studio and ended up with this mess.

Anyways, its fixed now.


Bei sowas wird git dann echt unübersichtlich...

**Pull request merged**
