### PR TITLE
Setting for idle speed

### PR DESCRIPTION
**Pull request by dennisguse**
... I prepared this some weeks ago, but it needs to be rebased.

### CODE REVIEW

**Comment by dennisguse** [comment]
needs to manually reapplied due to the refactorings in our settings.
Copy and paste seems easier than the merge conflicts :)

**Comment by dennisguse** [comment]
@vlmendz ready for testing :)

**Comment by vlmendz** [comment]
@dennisguse Tested and seems to work okay :). I only suggest adding the values 1.5, 2.5 and 3.5 km/h.

P.s. Confirmed the existence of a bug in track recording. I will work on the issue ( hopefully it will be simple to solve).

**Comment by dennisguse** [comment]
I added the requested options :)

PS/ nice for diving into it :D

**Pull request merged**
