### PR TITLE
StringUtilsTest.testFormatDateTime

### PR DESCRIPTION
**Pull request by rgmf**
Trying to fix strange fails in this test.

### CODE REVIEW

**Comment by rgmf** [comment]
@dennisguse what do you think?

We are doing something like this:

```java
"Jan 2, 2022 10:30:15 AM".contains("Jan 2, 2022 10:30:15")
```

So we are ignoring AM/PM/a.m./p.m. at the end of the string. I think it's not that important, at least we are sure the datetime is a "good" datetime.

**Review by dennisguse — APPROVED** [review]
Looks good :)

**Comment by dennisguse** [comment]
Well oehm my LineageOS still disagree: 
```
java.lang.AssertionError: Jan 2, 2022 10:15:30 vs Jan 2, 2022, 10:15:30 AM
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
```

using the following assert:
```
        assertTrue(expectedFormat + " vs " + formatDate, formatDate.contains(expectedFormat));
```


I am somehow start to believe, we should just remove this test...

**Comment by rgmf** [comment]
> I am somehow start to believe, we should just remove this test...

Yes, it's too much unpredictable and it shoudn't.

We are using official Java library but formatter results in different results depending on the device. I can't understand what's happening :disappointed:

**Comment by dennisguse** [comment]
Sometimes it is just confusing and we have to deal with it :)

**Pull request merged**
