### PR TITLE
Bugfix: running sensor data total is distance is UINT_32.

### PR DESCRIPTION
**Pull request by dennisguse**
End of cycling season and I started running again using a shoe-based running sensor.
... and reported distance got negative happened 2 or 3 times.
And today, I checked the parsing code and is an overflow that happened every 6.5km (UINT16 in decimeter).
But it should be a UINT32 :/

### CODE REVIEW

**Comment by dennisguse** [comment]
@rgmf @pstorch After merging this, I would create v3.22.0 - any more stuff to merge?

**Comment by rgmf** [comment]
> @rgmf @pstorch After merging this, I would create v3.22.0 - any more stuff to merge?

Go ahead.

**Comment by dennisguse** [comment]
Will do after a test run tomorrow :)

**Comment by rgmf** [comment]
> Will do after a test run tomorrow :)

Have a good run ;)

**Comment by dennisguse** [comment]
PS: I just want to facepalm myself by about this issue :/
And the parsing for the cycling sensor is also broken......

Stay tuned

Note to myself: don't trust your own work.
And

**Comment by dennisguse** [comment]
Post mortem to this issue:
The data via BLE is encoded as 4 byte and so far we only decoded the first 2 bytes (UINT16).
As this contains the LSO part, it seemed correct while testing, but leads to an overflow that is not handled properly (due to ignoring the MSO part).
In addition, we are not interested in the total distance of the sensor, but the total distance of the current track.

From the spec:
```
 The fields in the above table are in the order of LSO to MSO. Where LSO = Least Significant Octet and MSO = Most Significant Octet. 
```

@rgmf @FYI

**Comment by dennisguse** [comment]
Works :D

**Pull request merged**
