### PR TITLE
Bugfix: PublicAPI StartRecording recorded no data.

### LINKED ISSUE #1904: When starting OpenTracks via GadgetBridge no data is being recorded
When starting a new recording with my Mi Band 7 via Gadgetbridge a new recording is being started with opentracks but directly after the start stopped and no data is being recorded.

I know from old recordings that is worked until at least 2024-03-02, I just discovered that all other recordings are empty since then.

This is only the case when started via Gadgetbridge (via intent?), normal recording works. I checked all the settings, they seem to be correct.

...

**Checklist**

- [x] Consulted [https://dontkillmyapp.com/]
- [X] Power management: battery optimization is disabled for OpenTracks

**Technical information**

- Device: Pixel 7
- OS: GrapheneOS
- OpenTracks version: 4.12.2

### PR DESCRIPTION
**Pull request by dennisguse**
Problem was that the TrackRecordingService was not started as a ForegroundService anymore.

Fixes #1904.

### CODE REVIEW

**Comment by arjan-s** [comment]
This is great! Thank you!

**Comment by dennisguse** [comment]
@arjan-s hope it works :)
If you encounter anything broken, just let me know.

**Comment by arjan-s** [comment]
Just wanted to let you know it works perfectly again. Thanks!

**Comment by dennisguse** [comment]
@arjan-s thanks for the feedback :)

**Pull request merged**
