### PR TITLE
Moving time#1046

### PR DESCRIPTION
**Pull request by dennisguse**
Reverting changes to fix moving time issue.

### CODE REVIEW

**Comment by dennisguse** [comment]
@vlmendz Could you take a look at this PR?
Context can be found here: #1046.
When switching from idle to non-idle, we (again) store the last non-idle TrackPoint.
Feels like we need to switch back to this old idle/non-idle code :/

@rgmf I re-implemented the idle/non-idle code slightly different and added test coverage.

PS/ zero real-world testing done so far (just added one test case).

**Comment by rgmf** [comment]
> @rgmf I re-implemented the idle/non-idle code slightly different and added test coverage.
> 
> PS/ zero real-world testing done so far (just added one test case).

I'll test it tomorrow driving to work ;)

**Comment by rgmf** [comment]
@dennisguse it works like a charm but something strange happens:

- Start an activity.
- Stop after 15:03. **Moving Time: 15:03.**
- Resume for only a few seconds (2 seconds, for example). **Moving Time: 15:05.**
- Stop. **Moving Time: 15:05.**
- Resume again after a few seconds. **Moving Time begins from 15:03 instead of 15:05.**

It's an edge case and I think it's not that important, but if it's easy to fix it'd be great.

**Comment by dennisguse** [comment]
@vlmendz Correct, we would be re-adding idle/non-idle TrackPoints.
What would be your alternative proposal?
And so far, we compute the moving time only on stored TrackPoints - this allows to re-compute the same time on import.

**Comment by dennisguse** [comment]
@rgmf Not yet sure; the whole code sucks :D

**Comment by vlmendz** [comment]
@dennisguse I was now reading #1046 issue. My proposal is to calculate the time in motion by adding the duration of the segments where ismoving() is true (for both points of the segment, the initial and final point).

**Comment by dennisguse** [comment]
The problem is that we do not store TrackPoints that are not moving anymore... and we only segment using traveled distance, but on speed.

**Comment by rgmf** [comment]
> @rgmf Not yet sure; the whole code sucks :D

I couldn't guess what the problem is. For me is fine.

**Review by rgmf — APPROVED** [review]

**Comment by vlmendz** [comment]
I see no problem in this, while the speed is greater than the threshold, the duration of the segments is added.
When the speed drops below, nothing happens.
When the speed is again greater than the threshold, the recording resumes and the duration of the segments continues to be added. 
The time that the stop lasted is not added

**Comment by dennisguse** [comment]
@vlmendz exactly for this, we need to store additional TrackPoints (to segment idle/non-idle).
@rgmf The TrackStatisticsUpdater is processing the TrackPoints in an interesting, but inconsistent way.
My current assumption: if the current TrackPoint is moving, then add the time difference to the previously-stored one to moving time.
I added a test case how I assume it should work.

**Comment by vlmendz** [comment]
@dennisguse For example, imagine that you just want to determine the time in motion using a GPS, and you are not interested in recording the locations...

**Comment by dennisguse** [comment]
@rgmf This code should work.
Test coverage is there; didn't do a test drive.
OpenTracks now stores a TrackPoint if moving vs. is different regarding the lastStoredTrackPoint.
And the TrackStatisticsUpdater got revamped - interestingly this fixes issues with the GPX ExportImportTest with the TrackStatistics.

PS/ need to actually provide useful commits messages :)

**Comment by dennisguse** [comment]
This should now be working again.

@rgmf @pstorch @vlmendz Can you give this a spin and check that OpenTracks behaves nicely?

**Review by rgmf — APPROVED** [review]
Great for me. I've driven to work this morning with OT and I've not been able to reproduce the issue I pointed out to you a couple of days ago :partying_face:

**Comment by pstorch** [comment]
Hmm, run this branch on a short trip. 
Some strange observation: I started a track, put the phone in my pocket, rode a few km with the bike, opened OT and all numbers were still 0 (no track points recorded?). I stopped the track, when shopping, resumed the track and rode home. There I stopped again. This time the numbers shown seem to be correct. But when I went back to the track list, I saw that a recording was still active. I opened the  active track again and stopped a second time.

This behavior (stopping a track, but in the track list it is still running) could be reproduced a second time, but not the third time. As I was on the road, I haven't got a logcat.

**Comment by pstorch** [comment]
I was able to reproduce again. Starting the track recording, push the power button, so the screen of you phone turns black and OT runs in the background. Wait until the first notification. Then unlock the phone again and stop the recording. Go back to the track list and you see that there is still a track recording running.

This is the logcat:

```

2021-12-17 14:48:34.411 29612-29612/de.dennisguse.opentracks.debug E/ActivityThread: Service de.dennisguse.opentracks.services.TrackRecordingService has leaked ServiceConnection android.speech.tts.TextToSpeech$Connection@284d451 that was originally bound here
    android.app.ServiceConnectionLeaked: Service de.dennisguse.opentracks.services.TrackRecordingService has leaked ServiceConnection android.speech.tts.TextToSpeech$Connection@284d451 that was originally bound here
        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1941)
        at android.app.LoadedApk.getServiceDispatcherCommon(LoadedApk.java:1813)
        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1792)
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1899)
        at android.app.ContextImpl.bindService(ContextImpl.java:1829)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:774)
        at android.speech.tts.TextToSpeech.connectToEngine(TextToSpeech.java:849)
        at android.speech.tts.TextToSpeech.initTts(TextToSpeech.java:819)
        at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:772)
        at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:751)
        at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:735)
        at de.dennisguse.opentracks.services.tasks.VoiceAnnouncement.start(VoiceAnnouncement.java:122)
        at de.dennisguse.opentracks.services.tasks.VoiceAnnouncementManager.restore(VoiceAnnouncementManager.java:62)
        at de.dennisguse.opentracks.services.tasks.VoiceAnnouncementManager.setFrequency(VoiceAnnouncementManager.java:105)
        at de.dennisguse.opentracks.services.TrackRecordingService$2.onSharedPreferenceChanged(TrackRecordingService.java:110)
        at de.dennisguse.opentracks.settings.PreferencesUtils.registerOnSharedPreferenceChangeListener(PreferencesUtils.java:81)
        at de.dennisguse.opentracks.services.TrackRecordingService.onCreate(TrackRecordingService.java:148)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4650)
        at android.app.ActivityThread.access$1700(ActivityThread.java:301)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2185)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
2021-12-17 14:48:34.429 29612-29612/de.dennisguse.opentracks.debug E/ActivityThread: Service de.dennisguse.opentracks.services.TrackRecordingService has leaked ServiceConnection android.speech.tts.TextToSpeech$Connection@c88b6db that was originally bound here
    android.app.ServiceConnectionLeaked: Service de.dennisguse.opentracks.services.TrackRecordingService has leaked ServiceConnection android.speech.tts.TextToSpeech$Connection@c88b6db that was originally bound here
        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1941)
        at android.app.LoadedApk.getServiceDispatcherCommon(LoadedApk.java:1813)
        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1792)
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1899)
        at android.app.ContextImpl.bindService(ContextImpl.java:1829)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:774)
        at android.speech.tts.TextToSpeech.connectToEngine(TextToSpeech.java:849)
        at android.speech.tts.TextToSpeech.initTts(TextToSpeech.java:819)
        at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:772)
        at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:751)
        at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:735)
        at de.dennisguse.opentracks.services.tasks.VoiceAnnouncement.start(VoiceAnnouncement.java:122)
        at de.dennisguse.opentracks.services.tasks.VoiceAnnouncementManager.restore(VoiceAnnouncementManager.java:62)
        at de.dennisguse.opentracks.services.tasks.VoiceAnnouncementManager.setFrequency(VoiceAnnouncementManager.java:100)
        at de.dennisguse.opentracks.services.TrackRecordingService$2.onSharedPreferenceChanged(TrackRecordingService.java:107)
        at de.dennisguse.opentracks.settings.PreferencesUtils.registerOnSharedPreferenceChangeListener(PreferencesUtils.java:81)
        at de.dennisguse.opentracks.services.TrackRecordingService.onCreate(TrackRecordingService.java:148)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4650)
        at android.app.ActivityThread.access$1700(ActivityThread.java:301)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2185)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
2021-12-17 14:48:58.117 29612-29612/de.dennisguse.opentracks.debug I/ViewRootImpl@cb16c8c[TrackRecordingActivity]: stopped(false) old=true
2021-12-17 14:48:58.145 29612-29612/de.dennisguse.opentracks.debug I/TrackRecordingServiceConnection: Binding the service.
2021-12-17 14:48:58.167 29612-29612/de.dennisguse.opentracks.debug I/ViewRootImpl@cb16c8c[TrackRecordingActivity]: stopped(false) old=false
2021-12-17 14:48:58.167 29612-29612/de.dennisguse.opentracks.debug I/TrackRecordingServiceConnection: Starting the service.
2021-12-17 14:48:58.168 29612-9847/de.dennisguse.opentracks.debug I/TrackDataHub: Not reloading track 46
2021-12-17 14:48:58.169 29612-29612/de.dennisguse.opentracks.debug I/TrackRecordingServiceConnection: Binding the service.
2021-12-17 14:48:58.169 29612-29612/de.dennisguse.opentracks.debug W/TrackRecordingActivity: could not get TrackRecordingService
2021-12-17 14:48:58.170 29612-29612/de.dennisguse.opentracks.debug I/TrackRecordingServiceConnection: Binding the service.
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err: java.lang.NoSuchFieldException: stats_custom_layout_fields_default_value_19
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at java.lang.Class.getField(Class.java:1604)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at de.dennisguse.opentracks.settings.PreferencesUtils.getMultiTypedArray(PreferencesUtils.java:564)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at de.dennisguse.opentracks.settings.PreferencesUtils.buildDefaultFields(PreferencesUtils.java:578)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at de.dennisguse.opentracks.settings.PreferencesUtils.buildDefaultLayout(PreferencesUtils.java:584)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at de.dennisguse.opentracks.settings.PreferencesUtils.getCustomLayout(PreferencesUtils.java:595)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at de.dennisguse.opentracks.fragments.StatisticsRecordingFragment.lambda$new$0$de-dennisguse-opentracks-fragments-StatisticsRecordingFragment(StatisticsRecordingFragment.java:70)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at de.dennisguse.opentracks.fragments.StatisticsRecordingFragment$$ExternalSyntheticLambda0.onSharedPreferenceChanged(Unknown Source:2)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at de.dennisguse.opentracks.settings.PreferencesUtils.registerOnSharedPreferenceChangeListener(PreferencesUtils.java:81)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at de.dennisguse.opentracks.fragments.StatisticsRecordingFragment.onResume(StatisticsRecordingFragment.java:128)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at androidx.fragment.app.Fragment.performResume(Fragment.java:3039)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:607)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:306)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:3086)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:273)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:458)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:447)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:240)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at android.app.Activity.performResume(Activity.java:8378)
2021-12-17 14:48:58.179 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4897)
2021-12-17 14:48:58.180 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4944)
2021-12-17 14:48:58.180 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
2021-12-17 14:48:58.180 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
2021-12-17 14:48:58.180 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
2021-12-17 14:48:58.180 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
2021-12-17 14:48:58.180 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2021-12-17 14:48:58.180 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at android.os.Looper.loop(Looper.java:246)
2021-12-17 14:48:58.180 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8633)
2021-12-17 14:48:58.180 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-12-17 14:48:58.180 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
2021-12-17 14:48:58.180 29612-29612/de.dennisguse.opentracks.debug W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
2021-12-17 14:48:58.180 29612-29612/de.dennisguse.opentracks.debug E/PreferencesUtils: stats_custom_layout_fields_default_value_19
2021-12-17 14:48:58.182 29612-29612/de.dennisguse.opentracks.debug I/TrackRecordingServiceConnection: Binding the service.
2021-12-17 14:48:58.207 29612-29612/de.dennisguse.opentracks.debug I/SurfaceControl: assignNativeObject: nativeObject = 0 Surface(name=null)/@0x4f8f642 / android.view.SurfaceControl.readFromParcel:1117 android.view.IWindowSession$Stub$Proxy.relayout:1820 android.view.ViewRootImpl.relayoutWindow:9005 android.view.ViewRootImpl.performTraversals:3360 android.view.ViewRootImpl.doTraversal:2618 android.view.ViewRootImpl$TraversalRunnable.run:9971 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995 
2021-12-17 14:48:58.208 29612-29612/de.dennisguse.opentracks.debug I/SurfaceControl: nativeRelease nativeObject s[517925215088]
2021-12-17 14:48:58.208 29612-29612/de.dennisguse.opentracks.debug I/SurfaceControl: nativeRelease nativeObject e[517925215088]
2021-12-17 14:48:58.209 29612-29612/de.dennisguse.opentracks.debug I/ViewRootImpl@cb16c8c[TrackRecordingActivity]: Relayout returned: old=(0,0,1080,2280) new=(0,0,1080,2280) req=(1080,2280)0 dur=15 res=0x7 s={true 522757871376} ch=true fn=-1
2021-12-17 14:48:58.213 29612-29612/de.dennisguse.opentracks.debug I/ViewRootImpl@cb16c8c[TrackRecordingActivity]: [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:10957 android.view.ViewRootImpl.performTraversals:3845 android.view.ViewRootImpl.doTraversal:2618 
2021-12-17 14:48:58.213 29612-29612/de.dennisguse.opentracks.debug I/ViewRootImpl@cb16c8c[TrackRecordingActivity]: [DP] pd() Asnyc report
2021-12-17 14:48:58.224 29612-29612/de.dennisguse.opentracks.debug I/ViewRootImpl@cb16c8c[TrackRecordingActivity]: [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$performDraw$1$ViewRootImpl:4668 android.view.-$$Lambda$ViewRootImpl$DJd0VUYJgsebcnSohO6h8zc_ONI.run:6 android.os.Handler.handleCallback:938 
2021-12-17 14:48:58.224 29612-29612/de.dennisguse.opentracks.debug I/ViewRootImpl@cb16c8c[TrackRecordingActivity]: [DP] rdf()
2021-12-17 14:48:58.233 29612-29612/de.dennisguse.opentracks.debug I/TrackRecordingService: new status null -> RecordingStatus{trackId=null, paused=false}
2021-12-17 14:48:58.234 29612-29612/de.dennisguse.opentracks.debug D/VoiceAnnouncement: Start
```

Hope you can make any sense out of it.

**Comment by vlmendz** [comment]
I downloaded nightly apk #247 and as soon as I can I will test the recording (possibly tomorrow). For now I found some small problems that I put here in case you have not noticed them and want to correct them before the next release.

I was forced to uninstall the nightly apk I had installed (20211114) because the current one had a lower version. When reconfiguring the options:

1) The export folder remains as "Undefined" after selecting it.

2) The option "Instant Export..." remains disabled.

Screenshot_2021-12-17-13-20-21-876_de dennisguse opentracks nightly_1
☝️Screen after the export folder is selected
(Actually, folder selection works internally. I created a track of a few seconds, exported it manually and the file was created in the selected folder)


3) The value and description do not appear below the "Idle speed threshold" option:
Screenshot_2021-12-17-13-19-52-232_de dennisguse opentracks nightly_1

**Comment by dennisguse** [comment]
@pstorch created a new issue for this as this should not be related with this PR.
@vlmendz Jupp, the Github nightlies usually require a clean installation (i.e., wiping data).
Should not be related to this PR as well.

**Comment by dennisguse** [comment]
@rgmf @pstorch Any ideas why this test fails on API23 while it works on API30 (also locally on all API levels)?
The tests mocks everything (especially time) and should not result in a different result.
But somehow API23 losses one second __while__ recording...
I ran out of ideas.
https://github.com/OpenTracksApp/OpenTracks/runs/4570407966?check_suite_focus=true#step:4:252

**Comment by vlmendz** [comment]
Recording test results:
1) Moving time: Okay
2) Recorded locations: Same behavior as with versions prior to 3.22

Screenshot_2021-12-18-22-38-19-499_de dennisguse opentracks nightly_1

Captura ini1
☝️2-minute stop in the center of the circles (the distance between the circles is 5 meters, equal to that used as distance interval for recording).

Captura ini3
☝️Track Comparison: In green, recorded with OT 3.22; in another color, recorded with nightly apk #257.

**Comment by rgmf** [comment]
> @rgmf @pstorch Any ideas why this test fails on API23 while it works on API30 (also locally on all API levels)? The tests mocks everything (especially time) and should not result in a different result. But somehow API23 losses one second **while** recording... I ran out of ideas. https://github.com/OpenTracksApp/OpenTracks/runs/4570407966?check_suite_focus=true#step:4:252

The long story short: I'm trying to figuring out what's happening but it's really, really strange.

I can reproduce that test fail on my local machine, API 24. And here come the really strange story:
- If I launch all tests then I get the same error: `expected:<PT19M> but was:<PT18M>`
- If I only launch that test from AndroidStudio then I get other error in other line of that method: `expected:<PT55M> but was:<PT49M>`

**Comment by dennisguse** [comment]
@rgmf Nice that you can reproduce this locally ;)
So, somehow the mocking for the time gets messed up.
One idea: could check what values are in `TrackStatistics.startTime` and `TrackStatistics.stopTime`?
Somehow, somebody is interfering with the mocking and it might help to know those values as obviously they are different between API23/24 and API30.

@vlmendz Yes, looks like the previous behavior.
What speed do you use as idle speed threshold?
The doubled points on the blue track should not all occur, right?
Could you check how the speed for some subsequent points is?
I mean to be stored they should change between above idle speed and below idle speed.

**Comment by rgmf** [comment]
@dennisguse here they are:

At the beginning of the test:

```
Start Time: 1970-01-01T00:00:00Z
Stop Time: 1970-01-01T00:00:00Z
```

Just before  `expected: <PT19M> but was:<PT18M>` fail:

```
Start Time: 1970-01-01T00:00:00Z
Stop Time: 1970-01-01T00:19:00Z
```

Only FYI: this is the code I wrote:

```java
170. Log.e("probando", "Start Time: " + contentProviderUtils.getTrack(trackId).getTrackStatistics().getStartTime());
171. Log.e("probando", "Stop Time: " + contentProviderUtils.getTrack(trackId).getTrackStatistics().getStopTime());
172. assertTotalTime.apply(19 * 60);
```

**Comment by rgmf** [comment]
@dennisguse even worst. Launching only `TrackRecordingServiceTestStatistics.movingtime_with_pauses` test, here are the results:

Logs just before `expected:<PT55M> but was:<PT49M>` fail (last line of that method: 191): 

```
Start Time: 1970-01-01T00:00:00Z
Stop Time: 1970-01-01T00:50:00Z
```

**Comment by vlmendz** [comment]
@dennisguse I use 2.5 km/h. The speed at consecutive points is generally the same and greater than the threshold (about 1.5 m/s=5.4 km/h).

In the old idle/non-idle logic, the first point of these pairs was always recorded, whenever a point (the second of the pair) complied with the speed and distance filters. It seems like the same thing is happening now.

**Comment by dennisguse** [comment]
@rgmf @pstorch (as expected) this restores the previous behavior of v3.21.X.
I did today a test hike (about 16km on my default track) and compared to the nightly as well as v3.22.0: it looks okayish.
My proposal: merge this and create a release it somehow feels ugly that this is not working anymore.
I guess, we then can go back and try some fine-tuning afterwards - and also figure out why API23/24 tries to drive me nuts ;)

@vlmendz mhhhhhhh - likely we need something fancier than just the GPS speed for idle/non-idle detection.
Was even thinking about using the speedbuffer or at least have a minimal duration before switching.
But we need to move this discussion somewhere else ;)

**Comment by vlmendz** [comment]
@dennisguse Maybe the phone's accelerometers could be used? At least I have 0 experience in its use and my doubts of its usefulness in this type of application.

Moreover, GPS speed is doing its job well. In my opinion, the problem here is the current logic (I recorded a few tracks with OT 3.22, including some stops of more than half an hour, and the motion detection worked perfectly).

I'm thinking about some changes in the recording logic. The goal is to record only the first and last point during stops (so as not to break the current calculation of moving time). Take a look at the logic in the following snippet of (pseudo)code, it seems to me that it might work 🤨


      void onNewTrackPoint() {
      .
      .
        // Always insert the first segment location
        if (!currentSegmentHasTrackPoint()) {
            PreviousPoint_IsMovig = trackPoint.isMoving();
            RecordPoint(trackPoint);
            PreviousPoint = trackPoint;
            return;
        }
        .
        .
        If trackPoint.isMoving() then 
        {
          if (distanceToLastTrackLocation.greaterOrEqualThan(recordingDistanceInterval) then
          {
            if PreviousPoint_IsMovig = false then 
            {
              PreviousPoint_IsMovig = true;
              RecordPoint(PreviousPoint);
            }
            RecordPoint(trackPoint);
          }
        }
        else  
        {
          if PreviousPoint_IsMovig then 
          {
            PreviousPoint_IsMovig = false;
            RecordPoint(trackPoint);
          }
          PreviousPoint = trackPoint;
        }
    }

**Comment by dennisguse** [comment]
@rgmf @pstorch I would like to merge this today and release it.
Any blockers?

PS/ I disabled the test on API23, so CI should be green.

@vlmendz We need to move this discussion to a separate issue as it is kind of hard to keep track of multiple things in one stream. Can you create a new issue for this?

**Comment by rgmf** [comment]
> Any blockers?

Nope... Go ahead for me.

**Pull request merged**
