### PR TITLE
issue 122

### PR DESCRIPTION
**Pull request by rgmf**
# Thanks for your contribution.

**Describe the pull request**
I have done the issue 122 tagged as "good first issue". Now, when you are tracking you can add a marker through a gallery image. Also the image is copied to the app internal storage, so the app ask to the user for storage access permission.

**Link to the the issue**
https://github.com/OpenTracksApp/OpenTracks/issues/122

**License agreement**
By opening this pull request, you are providing your contribution under the _Apache License 2.0_ (see [LICENSE.md](LICENSE.md)).

### CODE REVIEW

**Comment by dennisguse** [comment]
Awesome!
@rgmf Could you send me an APK for testing?
I don't have a computer for the next few weeks.

**Comment by dennisguse** [comment]
One problematic thing: legacy storage permission should not be used. Some weeks ago, OpenTracks was migrated to Storage Access Framework. And thus read and write external storage permissions could be removed.

**Comment by rgmf** [comment]
> One problematic thing: legacy storage permission should not be used. Some weeks ago, OpenTracks was migrated to Storage Access Framework. And thus read and write external storage permissions could be removed.

Oops!! Ok, I didn't know it. That's great. I'm going to work on it and change it.

When I'll develop it I can send you an APK if you want.

**Comment by rgmf** [comment]
> One problematic thing: legacy storage permission should not be used. Some weeks ago, OpenTracks was migrated to Storage Access Framework. And thus read and write external storage permissions could be removed.

I close this pull request and open a new one with all new job done. Now, when user click on "Insert Photo" option the app ask to the user what to do: take a photo o select an image from the Gallery. Also, It's not necessary Storage permission because I have used SAF (Storage Access Framework).

**Pull request closed without merging**
