### PR TITLE
Proposed solution for recording points that do not meet filter conditions

### PR DESCRIPTION
**Pull request by vlmendz**
# Thanks for your contribution.

**Describe the pull request**
Proposed solution to #1007 

**Link to the the issue**
https://github.com/OpenTracksApp/OpenTracks/issues/1007#issue-1041879140

**License agreement**
By opening this pull request, you are providing your contribution under the _Apache License 2.0_ (see [LICENSE.md](LICENSE.md)).

### CODE REVIEW

**Comment by dennisguse** [comment]
Yes, you are right that is the code that creates these additional TrackPoints.
Storing these additional TrackPoints is not required for the sensor data.

PS: If you now setup AndroidStudio, you can execute the tests (using the emulator) and see the difference (some tests are failing with those changes). Failing tests are in TrackRecordingServiceTestLocation.
Because now we need to start discussing why/ if we need to store these TrackPoints or not or just in some cases.

One test case result: 
```
java.lang.AssertionError: Expected: [time=null (type=SEGMENT_START_MANUAL(-2)), time=null (type=TRACKPOINT(0)): lat=45.0 lng=35.0 acc=Distance{distance_m=1.0}, time=null (type=TRACKPOINT(0)): lat=45.0 lng=35.0 acc=Distance{distance_m=6.0}, time=null (type=SEGMENT_END_MANUAL(1))]
actual: [time=2021-11-03T21:44:16.716Z (type=SEGMENT_START_MANUAL(-2)), time=2021-11-03T21:44:16.766Z (type=TRACKPOINT(0)): lat=45.0 lng=35.0 acc=Distance{distance_m=1.0}, time=2021-11-03T21:44:16.806Z (type=SEGMENT_END_MANUAL(1))]
at de.dennisguse.opentracks.io.file.importer.TrackPointAssert.assertEquals(TrackPointAssert.java:86)
at de.dennisguse.opentracks.services.TrackRecordingServiceTestLocation.testOnLocationChangedAsync_idle_withMovement(TrackRecordingServiceTestLocation.java:292)
```

**Comment by vlmendz** [comment]
As I see it, storing these GPS TrackPoints breaks the operation of the filters, and as a consequence produces unwanted side effects in track recording.

@dennisguse for now I can't install Android Studio. Wouldn't it be better to assign this PR to someone with conditions to perform these tests?

**Comment by dennisguse** [comment]
Failing tests are expected (actually a good thing as we are testing this functionality). One approach would be to check the test (especially the one that fail) and check if the difference makes sense (i.e., is desired).

For me, this has a low priority.
So, it might take until next year.
Other (also non-OpenTracks) things are at the moment with a higher priority :man_shrugging: 

PS/ does not seem to be urgent as we have this functionality in the code since years.

PS/ actually Github should execute the tests, but it isn't starting them (and I cannot trigger it manually) for Pull Requests from forked repositories.
I will look into this.

**Comment by vlmendz** [comment]
@dennisguse Good day, today I reread the code, taking into account what you wrote above ("Storing these additional TrackPoints is not required for the sensor data."). It seems to me that this related lastTrackPoint code is basically reminiscent of the old idle/non-idle code.

Assuming this, I modified the code again, removing everything related to the storage of lastTrackPoint. Now the code is somewhat simpler, and some energy could be saved (at least theoretically).

P.s. Possibly now only one of the functions (insertTrackPoint or insertTrackPointHelper) would be necessary. I kept both because I don't know if they're used anywhere else.

**Comment by dennisguse** [comment]
After some heavy thinking: I agree that code is doing something but is not really useful (anymore).
Removing this, simplifies the recording code a lot (even getting rid of the trouble with cumulative sensor data that was fixed with v3.21.0).

Their is one edge case though: if a user pauses/stops a track it would be slightly more correct to store lastTrackPoint (if it wasn't stored so far; and ignore if the recording distance intervals is larger than the threshold).
In this case, we have received a location, but ignored it (so far) and might store as it is slightly closer to the user's final position than the one we stored beforehand.
With relatively low recording distance interval this is not really an issue: 10m (100m) distance threshold means, we would lose max 9.9m (99.9m).
IMHO: this is not worth the effort to keep this complexity around.

@pstorch @rgmf Usual question: did I miss something?
Could this code be useful for anything else?
PS/ test cases were initially created using the current implementation - without understanding it by me some time ago.
Just to prevent regressions due to refactoring.

@vlmendz I like your style on how you dig in the code base - it really triggers some thoughts :sunglasses: 
I adjusted the tests, removed other code that is then not used anymore.
As you still cannot compile yourself(?) and the nightly build is not triggered for you PRs (don't know why): APK is attached; signed with the PlayStore key.
[OpenTracksUpstream-releasePlayStore.zip](https://github.com/OpenTracksApp/OpenTracks/files/7492471/OpenTracksUpstream-releasePlayStore.zip)

**Comment by rgmf** [comment]
> With relatively low recording distance interval this is not really an issue: 10m (100m) distance threshold means, we would lose max 9.9m (99.9m). IMHO: this is not worth the effort to keep this complexity around.


I agree with yout. If user select a distance interval of 100m then user doesn't care about the precision, so 99.9m is not too much.

The code now seems simpler.

Great job @vlmendz

**Comment by vlmendz** [comment]
Their is one edge case though: if a user pauses/stops a track it would 
    be slightly more correct to store lastTrackPoint ...

As I see it, the key aspect here is to use appropriate values for filters. For example, with the current recording logic I can use a distance interval of 5m and a minimum speed of 2 km/h. These values allow to record a track in great detail and at the same time with practically no unnecessary locations/noise (even making multiple and/or long stops).

Therefore, the pause would only be necessary to continue a track in a different place from where it stopped (I like this feature of OpenTracks that creates a new segment when using the pause and when moving without a GPS fixation for a distance > = than a customizable maximum distance). 

    As you still cannot compile yourself(?) 

I can't compile yet 😟

    and the nightly build is not triggered for you PRs (don't know why)

This is the first PR I have created, so if you don't know why, what could I know 🤷🏻😀

    APK is attached; signed with the PlayStore key.

Downloaded and installed 👍

    I agree with yout. If user select a distance interval of 100m then user 
    doesn't care about the precision, so 99.9m is not too much.

Also agree 👌

P.s. Thanks :)

**Comment by dennisguse** [comment]
@vlmendz FYI: I will squash the commits (so only one commit will be merged.

And what can we do to enable you to compile yourself?
It is basically installing AndroidStudio and cloning the code :)

**Comment by dennisguse** [comment]
Damn: forgot to update the message.
Will create another commit locally.

**Comment by dennisguse** [comment]
Actual commit on main: https://github.com/OpenTracksApp/OpenTracks/commit/08ba7d50c73197a1230eca8cc72dc1d501d7a6af

**Pull request merged**
