### PR TITLE
Fix compatibility issue in styles_custom.xml

### PR DESCRIPTION
**Pull request by john2020star**
Adding indeterminateTintMode="src_in"

**Describe the pull request**
I have found there is a compatibility issue in styles_custom.xml. You forget to add `android:indeterminateTintMode="src_in"`, which can cause the color of ProgressBar not consistent when API Level < 23. This pull request help fix this issue.

### CODE REVIEW

**Comment by dennisguse** [comment]
Nice!
Do you have some insights why this is needed?

**Comment by john2020star** [comment]
Actually it is a bug of Android framework. [https://issuetracker.google.com/issues/37035006](url)

In API Level 22, the code in ProgressBar.java looks like this.
`if (a.hasValue(R.styleable.ProgressBar_indeterminateTint)) {
    // ...
    mProgressTintInfo.mIndeterminateTintMode = Drawable.parseTintMode(a.getInt(
                    R.styleable.ProgressBar_indeterminateTintMode, -1), null);
    // ...
}`
If you only set indeterminate, then the indeterminateTintMode will be wrongly applied with the default value even it is not set in the layout xml file, and it was fixed in API Level 23.

**Comment by john2020star** [comment]
I have added a new theme for the dialog to help you actually change the color of ProgressBar in the previous commits, because you need to manually set the style to ProgressDialog before API 22.

To test this, try to delete a track in API Level 22.
Before
image

After
image

It works well in API Level >= 23

**Comment by dennisguse** [comment]
+1

**Pull request merged**
