### PR TITLE
Proposed modifications to GPS speed processing

### PR DESCRIPTION
**Pull request by vlmendz**
# Thanks for your contribution.

**Describe the pull request**
For implement and testing the changes proposed in #1003 

**Link to the the issue**
https://github.com/OpenTracksApp/OpenTracks/issues/1003#issue-1040475586

**License agreement**
By opening this pull request, you are providing your contribution under the _Apache License 2.0_ (see [LICENSE.md](LICENSE.md)).

### CODE REVIEW

**Comment by vlmendz** [comment]
As I am not a Java programmer, i made a trivial change (comment  the declaration of speedBuffer_mps) to be able to create the PR.

Still to be done:
1) Completely remove the use of speedBuffer_mps

2) Reduce the value of MAX_ACCELERATION

3) Use for acceleration calculation the previous received location with a valid acceleration and not the lastTrackPoint

**Comment by dennisguse** [comment]
@vlmendz oehm - how can I help you installing AndroidStudio as you can obviously read some code?

**Comment by vlmendz** [comment]
@dennisguse I used the notepad++ and geany editors to read the code. 

To have a functional installation of Android Studio I require time and I am currently really busy.

Also, Android Studio is only part of the problem. As my knowledge of Java and OpenTracks code is very limited, this would demand considerably more time from me than from someone with a good knowledge of both.

I created this PR because you asked me to do it. I think that with what we have discussed from #994 to here, you could make the modifications without difficulties (you could start with the first two and leave the change in the calculation for later, in any case, we can always discuss any questions or ideas that appear).

**Comment by dennisguse** [comment]
I just wanted to briefly remove the `speedBuffer_mps`, but seemingly it is not a 5min excercise.
To remove it, we need to add the speed computation based upon the distance to previous TrackPoint first.

**Comment by vlmendz** [comment]
@dennisguse  I do not understand why you are referring to "add the speed computation based upon the distance to previous TrackPoint".

The idea here is to use the GPS speed (the one reported by the device). I thought it was this:

    trackPoint.getSpeed().toMPS()

(if not the previous one, somewhere the GPS speed is saved, because it is exported in gpx files)

**Comment by dennisguse** [comment]
Yes, that is the GPS (or rather sensor) provided speed.
I understood that the plan is to not use this for the statistics, but rather compute the speed using the current vs. previous location, right?

**Comment by vlmendz** [comment]
No, the plan is to use the GPS speed trackPoint.getSpeed() (it looks like my awful "english" is coming into play here). Please look again at the chart at #1003.

I partially modified a piece of code to try to make you better understand the idea (I put it below so I wouldn't be writing incomplete and possibly erroneous modifications to the current code):

    private void updateSpeed(@NonNull TrackPoint trackPoint, @NonNull TrackPoint lastTrackPoint) {
        if (!trackPoint.isMoving()) {
            //speedBuffer_mps.reset();
        } else if (isValidSpeed(trackPoint, lastTrackPoint)) {
            //speedBuffer_mps.setNext(trackPoint.getSpeed().toMPS());
            //Speed average = Speed.of(speedBuffer_mps.getAverage());    
            Speed GPSSpd = Speed.of(trackPoint.getSpeed().toMPS());            
            //if (average.greaterThan(currentSegment.getMaxSpeed())) 
            if (GPSSpd.greaterThan(currentSegment.getMaxSpeed())) 
            {
                currentSegment.setMaxSpeed(average);
            }
        } else {
            Log.d(TAG, "Invalid speed. speed: " + trackPoint.getSpeed() + " lastLocationSpeed: " + lastTrackPoint.getSpeed());
        }
    }

Note that speedBuffer_mps is removed to determine the maximum speed, and trackPoint.getSpeed() is used directly for this.

**Comment by dennisguse** [comment]
Like this?
https://github.com/OpenTracksApp/OpenTracks/pull/1026/commits/ea0ea9398f3439e4c609a8ae52b9bab69b7aacb6

PS/ did not test it

**Comment by vlmendz** [comment]
Yes, that's the idea

**Comment by dennisguse** [comment]
Closing this for now.

@vlmendz I added some real integration tests.
For all modifications of which TrackPoints to record and how to compute statistics like speed, we need some tests.
I implemented some (and found some other issues); you can take a look at TrackRecordingServiceTestRecording.
Each test consists of what happened (when) and what is expected (then).
We need to have something similar for complicated changes in the related code.

**Pull request closed without merging**
