### PR TITLE
Thrillfall instant export

### PR DESCRIPTION
**Pull request by dennisguse**
Follow-up to  #383.
Contains a big refactoring of the initial PR:
* removed separate thread for export and TrackRecordingService exports now in EndCurrentTrack (we might have gotten weird errors if the export thread would be long running while the TrackRecordingService context already got destroyed)
* unified export code between post-workout and export all
* unified directory chooser
* cleaned up settings xml
* fixed translations

The default export directory can now be unset by opening the directory chooser and then press back. 
This is not obvious but easy to implement.

@thrillfall could you test that this still works?

From my side ready to be merged.

### CODE REVIEW

**Comment by dennisguse** [comment]
Note: merge via create a merge commit.

**Comment by rgmf** [comment]
It works perfect for me. Nice feature :D

Great job @thrillfall

I'd merge it, what do you think @thrillfall @dennisguse?

**Comment by dennisguse** [comment]
Nobody complained :)

**Comment by dennisguse** [comment]
@thrillfall FYI: v3.12 (incl this feature) was today deployed on FDroid.

**Pull request merged**
