### PR TITLE
Aggregated statistics by activity type.

### PR DESCRIPTION
**Pull request by rgmf**
**Describe the pull request**
Added new Activity that shows aggregated statistics by activity type.

I've used ViewModel and LiveData to load aggregated stats from database in a ListView. Also, I've used a custom adapter to that ListView for handle different types of sports.

It shows for now:
- Number of activities per sport type.
- Total distance and time per sport type.
- Avg. speed or Avg. pace per sport type.
- Max. speed or Fastest pace per sport type.

In the future this Activity could be three tabs: one for all times stats, other one for monthly stats and last one for yearly stats. But for the first version I think it's enough for now.

I've added tests for new AggregatedStatistics class.

And, an screenshot:
image

**Link to the the issue**
https://github.com/OpenTracksApp/OpenTracks/issues/112

**License agreement**
By opening this pull request, you are providing your contribution under the _Apache License 2.0_ (see [LICENSE.md](LICENSE.md)).

### CODE REVIEW

**Comment by rgmf** [comment]
I used AsyncTask. In the last splash git commit I changed AsyncTas with Java's native implementation (https://github.com/OpenTracksApp/OpenTracks/issues/273)

**Comment by dennisguse** [comment]
@rgmf Why aggregate by icon and not by category (`track.getCategory()`).
This value is user changeable independent of the icon.
So, a user might decide to use the bicycle icon for MTB and race biking while settings the category differently.

**Comment by dennisguse** [comment]
@rgmf Can we avoid that `AggregatedStatistics`:
1. needs the context, and
2. that the orders of key in the map is used?

Usually maps are unsorted...

**Comment by rgmf** [comment]
> @rgmf Why aggregate by icon and not by category (`track.getCategory()`).
> This value is user changeable independent of the icon.
> So, a user might decide to use the bicycle icon for MTB and race biking while settings the category differently.

I was thinking about it but I decided to aggregate all in main categories (icon): bike, running, walking... But, you are right, for example if a user decides to split bike in MTB and Race Biking then OpenTracks should aggregate stats in MTB and Race Biking. I'll change it.

**Comment by rgmf** [comment]
> @rgmf Can we avoid that `AggregatedStatistics`:
> 
>     1. needs the context, and

Done.

> 
>     2. that the orders of key in the map is used?

Done.

> 
> 
> Usually maps are unsorted...

Also, aggregated stats uses category instead of icon to aggregate stats (this has more sense).

**Comment by dennisguse** [comment]
@rgmf Squash and merge?
I would include this change in the next release :)

**Comment by dennisguse** [comment]
@rgmf Then you need to push the button :)

**Comment by dennisguse** [comment]
@rgmf Wohoooo!

**Pull request merged**
