### PR TITLE
Track recording service#882

### PR DESCRIPTION
**Pull request by dennisguse**

### CODE REVIEW

**Comment by dennisguse** [comment]
@rgmf I started some internal refactoring (basically moving functionality out of TrackRecordingService) - this should not affect any UI. Should be latest ready next weekend.

**Comment by rgmf** [comment]
@dennisguse Okay, I'm finishing #842... I think/hope we're not touching the same files.

PS/ 42ºC temperature... so I'll finish it this afternoon, only brave people go out :rofl: :rofl:

**Comment by dennisguse** [comment]
@rgmf @pstorch For testing purposes, Github actions now stores the produced logs (the HTML produced by ./gradle connectedCheck) as an artifact (only in this branch for now; after merging also on main):
 https://github.com/OpenTracksApp/OpenTracks/pull/883/commits/e41e12733aab4c47f236a945cf23e8272fe2ad1f

We could also use this later for building APKs and making those available for testing.

**Comment by dennisguse** [comment]
@rgmf PR is ready (I hope); there a another billion changes that are necessary, but for now that is sufficient ;)

**Comment by dennisguse** [comment]
@rgmf PR is ready (I hope); there a another billion changes that are necessary, but for now that is sufficient ;)
It would be great if you could do some tests - I found some problems and did some nasty refactoring.
Hope I did repaired all the things I broke :)

**Comment by rgmf** [comment]
@dennisguse installed and ready to test... I'll inform you about my tests ;)

**Comment by rgmf** [comment]
@dennisguse it works very well for me. But only two tiny issues with layouts:

- When elevation is off in setting then gain/loss values are shown but not labels:
imagen

- Issue in recording layout: EGM2008 label is shows but it should be hidden when elevation is off in settings:
imagen

**Comment by dennisguse** [comment]
@rgmf Works for me :)

**Comment by rgmf** [comment]
@dennisguse a tiny bug in XML recording layout (`statistics_recording.xml`):

Line 272, it should be:

```xml
app:constraint_referenced_ids="stats_altitude_horizontal_line,stats_altitude_current_label,stats_altitude_current_value,stats_altitude_current_unit,stats_altitude_gain_label,stats_altitude_gain_value,stats_altitude_gain_unit,stats_altitude_loss_label,stats_altitude_loss_value,stats_altitude_loss_unit,stats_altitude_current_label_egm" />
```

instead of:

```xml
app:constraint_referenced_ids="stats_altitude_horizontal_line,stats_altitude_current_label,stats_altitude_current_value,stats_altitude_current_unit,stats_altitude_gain_label,stats_altitude_gain_value,stats_altitude_gain_unit,stats_altitude_loss_label,stats_altitude_loss_value,stats_altitude_loss_unit,@+id/stats_altitude_current_label_egm" />
```

Look at `@+id/stats_altitude_current_label_egm` that it should be: `stats_altitude_current_label_egm`

**Comment by dennisguse** [comment]
@rgmf Nice catch! ;)

**Review by rgmf — APPROVED** [review]
👍

**Pull request merged**
