### PR TITLE
Release v3.9.3

### PR DESCRIPTION
**Pull request by rgmf**
New release with bugfix.

**License agreement**
By opening this pull request, you are providing your contribution under the _Apache License 2.0_ (see [LICENSE.md](LICENSE.md)).

### CODE REVIEW

**Comment by dennisguse** [comment]
Probably not documented: https://github.com/OpenTracksApp/OpenTracks/releases
I usually create the TAG via Github releases (can also be done afterwards).

**Comment by rgmf** [comment]
@dennisguse I've tried to do it myself following the README_RELEASE.md. I hope it's okay :D

**Comment by dennisguse** [comment]
All perfect!

**Comment by dennisguse** [comment]
@rgmf I forgot to mention it, but you can also directly commit to `main`.
PRs are usually things that need discussion / approval / testing / whatever ><

**Pull request merged**
