### PR TITLE
TrackRecordingService: provide status updates via LiveData.

### PR DESCRIPTION
**Pull request by dennisguse**
Just some work in progress.

* [x] TrackRecordingActivity.
* [x] MarkerListActivity
* [x] TrackListActivity
* [x] TrackRecordedActivity
* [x] SettingsActivity.PrefsFragment

TODO: 
* [x] check if LiveData reference should be kept in subscribers
* [x] check what happens when subscribing multiple times: we get the event multiple times; not that problematic
* [x] check if object reference leaks
* [x] remove TrackRecordingServiceStatus

### CODE REVIEW

**Comment by dennisguse** [comment]
Stale references are not an issue: https://developer.android.com/topic/libraries/architecture/livedata
```
You can register an observer paired with an object that implements the LifecycleOwner interface. This relationship allows the observer to be removed when the state of the corresponding Lifecycle object changes to DESTROYED. This is especially useful for activities and fragments because they can safely observe LiveData objects and not worry about leaks—activities and fragments are instantly unsubscribed when their lifecycles are destroyed.
```

**Comment by dennisguse** [comment]
@rgmf @pstorch Could you give this a spin?

I hope I did not break too much....

**Comment by rgmf** [comment]
> @rgmf @pstorch Could you give this a spin?
> 
> I hope I did not break too much....

Installing it... and ready to check it out :smile: 

I'll use it this weekend and I'll tell you how it's going.

**Comment by pstorch** [comment]
I think I can also give it a try at the weekend.

**Comment by pstorch** [comment]
Anything special to look at?
A recording while a short walk to the bakery worked without issue.

**Comment by rgmf** [comment]
It works well for me, not any bug found, but only a strange issue in the  graph drawn. I don't know if it's related with this issue but looks like it is not:

Screenshot_20210430-173443_OpenTracks_(Debug)

**Comment by dennisguse** [comment]
@rgmf That is not related to this change.
Some weeks ago I was fixing this https://github.com/OpenTracksApp/OpenTracks/issues/42
This looks related.

And the elevation is broken: I can reproduce this; issue seems to be that the conversion is incorrect; this happened in this PR (I guess).

**Comment by rgmf** [comment]
@dennisguse after recording, back to list and GPS status remains with this icon:

Screenshot_20210501-204134_OpenTracks_(Debug)_1

**Comment by dennisguse** [comment]
@rgmf I added this commit to always update the GpsStatus, but I am not sure that this is the best solution.
And we seemingly get a delayed callback after TrackRecordingService.onDestroy() is called. I just catch this with a null check - not really cool: https://github.com/OpenTracksApp/OpenTracks/pull/736/commits/cc775655299a04fd087f7f42e4c40bcce433768d

**Comment by dennisguse** [comment]
@rgmf @pstorch Any more things that you found while testing?

**Comment by rgmf** [comment]
> @rgmf @pstorch Any more things that you found while testing?

I've not found any more things.

**Comment by pstorch** [comment]
> @rgmf @pstorch Any more things that you found while testing?

Nothing else from my side

**Comment by dennisguse** [comment]
@rgmf @pstorch Thanks! :partying_face:

**Pull request merged**
