### PR TITLE
Use AltitudeConverterCompat instead of custom solution.

### LINKED ISSUE #1920: Use AltitudeConverterCompat?
We may be able to strip all the custom code for Altitude correction for prior Android versions by using AltitudeConverterCompat. 

https://developer.android.com/reference/androidx/core/location/altitude/AltitudeConverterCompat

### PR DESCRIPTION
**Pull request by dennisguse**
Fixes #1920.

Implements fallback to EGM2008 up until API33 using Android's core library.

Aspects:
* core library is still in alpha mode
* data may still be bundled (not sure how big it is)

### CODE REVIEW

**Comment by dennisguse** [comment]
Android core location does include the data into the APK (`assets/database/geoid-height-map-v0.db`).
This file is about 80Kb and opened using Android ROOM (i.e., an SQLite database).

This will reduce the APK size by ~17MB.

**Comment by dennisguse** [comment]
@gdt if you have time, it would be great if you could try this out :)

**Comment by pstorch** [comment]
Haven't used OpenTracks for some time. I checked out this branch and went for a walk  
I started the recording. The notification indicated that it's running, but when I click on it, OpenTracks shows no running recording. 

I tried to start it again and got this error:

### App information
* ID: de.dennisguse.opentracks.debug
* Version: 5788 v4.12.4-debug

### Device information
* Brand: samsung
* Device: y2s
* Model: SM-G985F
* Id: TP1A.220624.014
* Product: y2seea

### Firmware
* SDK: 33
* Release: 13
* Incremental: G985FXXSKHXEA

### Cause of error
```java
Exception in thread "main": java.lang.IllegalStateException: Cannot access database on the main thread since it may potentially lock the UI for a long period of time.
	at androidx.room.RoomDatabase.assertNotMainThread(RoomDatabase.java:469)
	at androidx.room.RoomDatabase.query(RoomDatabase.java:525)
	at androidx.room.util.DBUtil.query(DBUtil.java:86)
	at androidx.core.location.altitude.impl.db.MapParamsDao_Impl.getCurrent(MapParamsDao_Impl.java:29)
	at androidx.core.location.altitude.impl.GeoidHeightMap.getParams(GeoidHeightMap.java:93)
	at androidx.core.location.altitude.impl.AltitudeConverter.addMslAltitudeToLocation(AltitudeConverter.java:199)
	at androidx.core.location.altitude.AltitudeConverterCompat.addMslAltitudeToLocation(AltitudeConverterCompat.java:86)
	at de.dennisguse.opentracks.services.handlers.AltitudeCorrectionManager.correctAltitude(AltitudeCorrectionManager.java:29)
	at de.dennisguse.opentracks.services.TrackRecordingManager.getDataForUI(TrackRecordingManager.java:128)
	at de.dennisguse.opentracks.services.TrackRecordingService.updateRecordingDataWhileRecording(TrackRecordingService.java:307)
	at de.dennisguse.opentracks.services.TrackRecordingService.-$$Nest$mupdateRecordingDataWhileRecording(Unknown Source:0)
	at de.dennisguse.opentracks.services.TrackRecordingService$1.run(TrackRecordingService.java:76)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by dennisguse** [comment]
@pstorch I just realized that I was using the SDK34 emulator all the time and there the fallback isn't used....
Need to check how to get this done :)
PS main thread is okay in this case.

**Comment by dennisguse** [comment]
@pstorch I reported this: https://issuetracker.google.com/issues/195660815#comment21
Let's hope the library gets adjusted - adding async behavior to this would make the code even messier.

**Comment by dennisguse** [comment]
@pstorch I added some `<airquote>`background`</airquote>` and it works in my emulator.
Not proud to have written this code...
Would you have some time to check this?

**Comment by pstorch** [comment]
I'll give it a try.

**Comment by pstorch** [comment]
The bug from last time is gone. I found another, but this is already in the main branch.

**Comment by dennisguse** [comment]
@pstorch which one? :D

**Comment by pstorch** [comment]
> @pstorch which one? :D

The crash I reported here:
https://github.com/OpenTracksApp/OpenTracks/pull/1931#issuecomment-2185070817

**Pull request merged**
