### PR TITLE
Performance: statistics fragment use sharedPreferenceListener

### PR DESCRIPTION
**Pull request by dennisguse**
While doing some cleanup, I was annoyed by the slowness of the statistics fragments.
Those repeatedly access  the sharedpreferences in a very non-performant manner.
Now, a listener is used and startup is way faster + the unwanted animation is gone.

### CODE REVIEW

**Review by rgmf — APPROVED** [review]
What a stupid thing I did with Preferences in fragment statistics!
Great catch and cleanup!!!

**Comment by dennisguse** [comment]
@rgmf Don't worry, wasn't you - the initial code was like this.
And the two of us just copied it and re-used it :)

**Comment by rgmf** [comment]
@dennisguse I didn't realize that pace of all activities are showed in min/km regardless the activity type. But if you move off from OT and back again then OT shows pace correctly.

**Comment by dennisguse** [comment]
@rgmf You are right: the callback from the activityChooser is handled by the TrackRecordingActivity, but this info is _not_ passed to the StatisticsRecordingFragment. We now update it if the track's category changes (which is triggered by the user's selection).

**Comment by rgmf** [comment]
> @rgmf You are right: the callback from the activityChooser is handled by the TrackRecordingActivity, but this info is _not_ passed to the StatisticsRecordingFragment. We now update it if the track's category changes (which is triggered by the user's selection).

Also for TrackRecordedActivity / StatisticsRecordedFragment...

**Comment by dennisguse** [comment]
@rgmf Done;
Also removed use of onActivityCreated (deprecated) and reordered the methods.

**Review by rgmf — APPROVED** [review]
It works for me.
PS/ Mental note: I need to pay attention to declare final the variables has to be final.

**Comment by dennisguse** [comment]
@rgmf I use AndroidStudio's static code analyzer every now and then - it shows such things and even fixes it almost automatically.
:)

**Comment by rgmf** [comment]
> @rgmf I use AndroidStudio's static code analyzer every now and then - it shows such things and even fixes it almost automatically.
> :)

Ummm, okay, I'm going to add that in my routine :smile:

**Comment by dennisguse** [comment]
@rgmf And at some point I would love to get rid of all the warnings AndroidStudio shows, but somehow they are not getting less :shrug:

**Comment by rgmf** [comment]
> @rgmf And at some point I would love to get rid of all the warnings AndroidStudio shows, but somehow they are not getting less shrug

:rofl: :rofl: :rofl: 

I'm going to try to help you on that.

**Pull request merged**
