### PR TITLE
forward keep screen on while recording preference to dashboard

### PR DESCRIPTION
**Pull request by pstorch**
Needed for: https://github.com/OpenTracksApp/OSMDashboard/pull/38

### CODE REVIEW

**Comment by dennisguse** [comment]
@pstorch Love it.
Can you also add show on lock screen?

https://github.com/OpenTracksApp/OpenTracks/blob/1f2e3bcf70f4b94547f5041a90f40bcb06a4ccd2/src/main/java/de/dennisguse/opentracks/TrackRecordingActivity.java#L241

**Comment by pstorch** [comment]
@dennisguse just in case for other dashboards, or should the OSMDashboard show something on the lock screen?

**Comment by dennisguse** [comment]
@pstorch the option allows to show an activity basically above the lock screen.
Thus, it is visible without unlocking the phone.
However, this only applies if the activity was focused by the user beforehand.
If it is the background, nothing happens.

**Comment by pstorch** [comment]
Added also the show on lockscreen preference. Good idea.

**Comment by pstorch** [comment]
@dennisguse ok to merge?

**Pull request merged**
