### PR TITLE
Refactor GPX and KML importer

### LINKED ISSUE #790: KML: order of gx:coord and when is not specified
**Is your feature request related to a problem? Please describe.**
We assume that:
```
<when>ASDF</when
<gx:coords>ASFD</gx:coords>
```

But the actual order of elements is not specified by the KML standard.
The elements might even be
```
<when>ASDF</when>
<when>ASDF</when>
<gx:coords />
<gx:coords />
```
It is only specified that the `count(when) === count(gx:coords)`.

https://developers.google.com/kml/documentation/kmlreference

**Describe the solution you'd like**
We need to adapt the KML parser as we have trouble to import KMLs from [GeoTracker](https://play.google.com/store/apps/details?id=com.ilyabogdanovich.geotracker).
GeoTracker starts with gx:coords alternating when.

### PR DESCRIPTION
**Pull request by dennisguse**
KML and GPX parsers were inherited from the same base class (AbstractTrackFileImporter).
Now both are independent of each other and the actual similar functionality moved into TrackImporter.
TrackImporter now takes care about all the things, we need to do to actually get a track:
* computing track statistics
* figuring out to which trackpoint a marker belongs
* speed (if not present in the data)
* determining TrackPoint.Type

This also fixes #790 (no test coverage for this yet).

### CODE REVIEW

**Comment by dennisguse** [comment]
@pstorch @rgmf 
I refactored the importer (or rather re-implemented them).
Could you check if this is still working :)
I don't have enough test data available.

I did this to fix #790.
GPX and KML are now independent (finally) and that should simplify maintenance!
PS: Actual import logic is now in TrackImporter - so we got rid of the inheritance :yeah:

**Comment by pstorch** [comment]
I will do some tests. Have enough files lying around 😉

**Comment by rgmf** [comment]
With my 215 recorded activities, I've got the same result than with older importer, so I guess it's working for me :tada: :tada:

**Comment by pstorch** [comment]
Ex- and Importing from the debug version worked, but the overall statistic was different at the end. Don't know why. Maybe I have some strange testcases in the debug database.

Exporting from the release version and importing into this debug version resulted in the following Exception:
```

    Caused by: java.lang.RuntimeException: stopTime cannot be less than startTime: 2020-07-26T08:51:20.573Z 2020-07-26T08:51:19.245Z
        at de.dennisguse.opentracks.stats.TrackStatistics.setStopTime(TrackStatistics.java:159)
        at de.dennisguse.opentracks.stats.TrackStatisticsUpdater.internalAddTrackPoint(TrackStatisticsUpdater.java:127)
        at de.dennisguse.opentracks.stats.TrackStatisticsUpdater.addTrackPoint(TrackStatisticsUpdater.java:112)
        at de.dennisguse.opentracks.stats.TrackStatisticsUpdater.addTrackPoints(TrackStatisticsUpdater.java:104)
        at de.dennisguse.opentracks.io.file.importer.TrackImporter.finishTrack(TrackImporter.java:143)
        at de.dennisguse.opentracks.io.file.importer.TrackImporter.finish(TrackImporter.java:123)
        at de.dennisguse.opentracks.io.file.importer.KmlTrackImporter.onFileEnd(KmlTrackImporter.java:423)
        at de.dennisguse.opentracks.io.file.importer.KmlTrackImporter.endElement(KmlTrackImporter.java:149)
        at org.apache.harmony.xml.ExpatParser.endElement(ExpatParser.java:167)
        at org.apache.harmony.xml.ExpatParser.appendBytes(Native Method)
        at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:526)
        at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:487)
        at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:324)
        at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:287)
        at javax.xml.parsers.SAXParser.parse(SAXParser.java:390)
        at javax.xml.parsers.SAXParser.parse(SAXParser.java:187)
        at de.dennisguse.opentracks.io.file.importer.XMLImporter.importFile(XMLImporter.java:46)
        at de.dennisguse.opentracks.io.file.importer.KmzTrackImporter.parseKml(KmzTrackImporter.java:222)
        at de.dennisguse.opentracks.io.file.importer.KmzTrackImporter.findAndParseKmlFile(KmzTrackImporter.java:160)
        at de.dennisguse.opentracks.io.file.importer.KmzTrackImporter.importFile(KmzTrackImporter.java:64)
        at de.dennisguse.opentracks.io.file.importer.ImportService.importFile(ImportService.java:69)
        at de.dennisguse.opentracks.io.file.importer.ImportService.onHandleWork(ImportService.java:49)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:391)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:382)
```

And Android told me the App keeps crashing.

**Comment by rgmf** [comment]
> but the overall statistic was different at the end. Don't know why. Maybe I have some strange testcases in the debug database.

Yes, overall statistics are different when you export/import. But if it's an issue it's not related with this PR because it happens with this new importer and with the older one.

I have very older tracks, recorded with older OT versions, so I don't know where the issue is either.

**Comment by dennisguse** [comment]
@rgmf @pstorch i hope the difference is not that big.
If it is only time and speed, then the old tracks do not contain SEGMENT_START_MANUAL and _END trackpoints.
We introduced this in v3.15.0 (Februrary 2021) and everything before or GPX will lead to slightly differences.

**Comment by dennisguse** [comment]
@rgmf @pstorch any more blockers on this?
Otherwise, I would merge and release tomorrow (and hope for the best :sunglasses:)....

**Review by rgmf — APPROVED** [review]
@dennisguse good for me ;)

**Pull request merged**
