### PR TITLE
New screenshots.

### PR DESCRIPTION
**Pull request by rgmf**
**Describe the pull request**
New screenshots.

These are the screenshots I would use. But I miss some screenshot about sensors but I don't have any. If you think it would be needed please send me all you want and I can prepare them.

Also, read and check it out the texts.

imagen

**Link to the the issue**
#562 

**License agreement**
By opening this pull request, you are providing your contribution under the _Apache License 2.0_ (see [LICENSE.md](LICENSE.md)).

**Note: new dependencies/libraries**
Please refrain from introducing new libraries without consulting the team.

### CODE REVIEW

**Comment by pstorch** [comment]
They look beautiful 😊

**Comment by FTno** [comment]
Nice screenshots, but there is an error in the text for the third screenshot:

.... take a photo o select ....
 (or select  -  I assume)

**Comment by rgmf** [comment]
> Nice screenshots, but there is an error in the text for the third screenshot:
> 
> .... take a photo o select ....
> (or select - I assume)

Ops!!! Yes, you are right! Thank you, I'll correct it.

**Review by dennisguse — APPROVED** [review]
Cool!

Did you use a script to convert the SVGs to PNGs?
If yes, we can for alter updates.

**Comment by rgmf** [comment]
> Cool!
> 
> Did you use a script to convert the SVGs to PNGs?
> If yes, we can for alter updates.

No, I didn't, but it sounds like a great idea. I had not thought of it.

I'm going to do it.

**Pull request merged**
