### PR TITLE
Gps Status: bugfixes.

### PR DESCRIPTION
**Pull request by rgmf**
**Describe the pull request**
Checking gps status out in a old smartphone I found two bugs:

- Bugfix 1: race condition issue fixed with a flag:
LocationHandler could call GpsStstatus multiple times and before GpsStatus could check the status.

- Bugfix 2: location time issue fixed setting the time every time a location is received:
Altough GpsStatus was called every second GpsStatus returned a bad gps signal because time diff between locations was about 14 seconds or more according to some tests in a smartphone.

**Testing**
I tested this PR with 4 phones (including the one with before errors) and the 4 ones work like a charm:

- Pixel 2 XL with Lineage 17.1
- Pixel 3a with Android 10.
- Huawei P20 Lite with Android 9.
- Sony Xperia XZ1 Compact with Lineage 16.2 (It's the one to blame for all this :D).

**License agreement**
By opening this pull request, you are providing your contribution under the _Apache License 2.0_ (see [LICENSE.md](LICENSE.md)).

### CODE REVIEW

**Comment by rgmf** [comment]
@dennisguse this PR is demanding because fix an important issue I discovered this morning testing the GpsStatus (the current main branch).

I rebase and merge it. Is there is something you don't like then I'll fix it.

**Comment by dennisguse** [comment]
@rgmf Do we need a new release?

**Comment by dennisguse** [comment]
Just saw your release comment, do you want to release or should I do it?

**Comment by dennisguse** [comment]
Done ;)

**Comment by rgmf** [comment]
> Done ;)

I couldn't do it now.

Thanks @dennisguse

**Comment by dennisguse** [comment]
@rgmf If you find something urgent bug and a quick fix, you can also create release.
I will then take care of the PlayStore.
You can take a look at README_RELEASE.md

**Pull request merged**
