### PR TITLE
Wahoo#1050

### LINKED ISSUE #1046: [v3.22.0]: Moving time is not working (everything is counted to moving time)
**Describe the bug**
Using nightly version I've figured out that moving time is not working. When you stopped the moving time stopped too, but then moving time jump forward all the time you was stopped.

For example:
- Start an activity and stopped after 30 minutes.
- Take a 5 minutes rest (moving time remains in 30 minutes).
- Resume the activity and then moving time jump to 35 minutes instead of continue from 30 minutes.

**To Reproduce**
Follow the example described above.

### LINKED ISSUE #1050: Wahoo blue SC sensor
This sensor has speed/distance sensor and also cadence sensor. The problem is that information from cadence is coming to speed/distance fields and speed info is coming to cadence field. Cadense field is still showing value in rpm, but it's following tyre rotation. If I stop rotating cranks, speed goes to zero.

### PR DESCRIPTION
**Pull request by dennisguse**
Fixes #1050 .

Will be merged ~before~ after v3.23.0.

### CODE REVIEW

**Comment by dennisguse** [comment]
@rgmf Can you check this with your Garmin sensors?
I just have a CSC, not the cadence one.

And I will check with a friend regarding Wahoo sensors.

**Comment by rgmf** [comment]
@dennisguse It works like a charm in Garmin Sensors (cadence and speed). I've tested it in 2 minutes indoor cycling activity.

PS/ Moving speed didn't work in this indoor activity (it remained at 00:00 all the time). It should be work, shouldn't it?

**Comment by dennisguse** [comment]
Thanks!
Then we can merge this.
Regarding moving time: it requires two consequent TrackPoints that are moving.
This requires #1033 if you did not get any GPS points.

**Comment by rgmf** [comment]
> This requires #1033 if you did not get any GPS points.

I thought #1033 was already merged :grin:, sorry

**Comment by dennisguse** [comment]
@rgmf #1033 is the direct next thing on my todo list :)

**Pull request merged**
