### PR TITLE
Bluetooth Sensor addresses shown while trying to connect

### PR DESCRIPTION
**Pull request by dennisguse**
So far, we updated (using sensor name and sensor data) the UI only when a sensor actually sent us data (so we are connected to it and the sensor can send data).
However, even if not connected to a sensor, we can show it's address in the UI.

### CODE REVIEW

**Comment by dennisguse** [comment]
PR is ready now.
I just moved to use ViewBindings in all fragments (now we have way less findViewById code ><).
I will check the activities after this PR is merged.

**Comment by dennisguse** [comment]
@rgmf @pstorch Any complains about this PR?
If not I would merge it and craft a release tomorrow (if you don't have anything reason(s) not to).

**Comment by pstorch** [comment]
> @rgmf @pstorch Any complains about this PR?

No and I can't even test it, I don't have a Bluetooth Sensor.

**Comment by rgmf** [comment]
> @rgmf @pstorch Any complains about this PR?
> If not I would merge it and craft a release tomorrow (if you don't have anything reason(s) not to).

I don't have any Bluetooth Sensor either.

**Comment by dennisguse** [comment]
@pstorch @rgmf  :+1:

**Pull request merged**
