### PR TITLE
added heart rate info to gpx export file

### PR DESCRIPTION
**Pull request by ronajon**
# Thanks for your contribution.

**Describe the pull request**
added extra heart rate information to GPX export file

**Link to the the issue**
(If available): The link to the issue that this pull request solves.

**License agreement**
By opening this pull request, you are providing your contribution under the _Apache License 2.0_ (see [LICENSE.md](LICENSE.md)).

### CODE REVIEW

**Comment by dennisguse** [comment]
Cool! Would you mind also adding the code for importing? Also we need an export-import test as implemented for KML/KMZ before we can merge it.

And why did you stats1.xml?

**Comment by dennisguse** [comment]
And we can also add cadence using the same GPX extension.

**Comment by ronajon** [comment]
> And we can also add cadence using the same GPX extension.

i've added cadence. 
https://github.com/OpenTracksApp/OpenTracks/commit/de2d39cb5a53e18772f121f50ecf7408958f337b

**Comment by ronajon** [comment]
> Cool! Would you mind also adding the code for importing? Also we need an export-import test as implemented for KML/KMZ before we can merge it.
> 
> And why did you stats1.xml?

i will have a look at the test. 
stats1 was another screen layout, with more focus on speed, heart rate

**Comment by dennisguse** [comment]
The tests are in `ExportImportTest.java`.

And one additional thought: `TrackFileFormat` defines only GPX.
I don't know if are really going to use this functionality, but for KML/KMZ different variants (amount of data included) were implemented.
Either we something similar for GPX as well or we check which of the KML/KMZ are actually used.

**Comment by dennisguse** [comment]
@ronajon Are you still working on this?

**Comment by ronajon** [comment]
> 
> 
> @ronajon Are you still working on this?

i have no clue how to write the tests for this ?

**Comment by dennisguse** [comment]
@ronajon I extended the existing tests to also verify the sensor data.
For GPX, this verification is disabled.
Just rebase onto `main`, enable the verification, and you will get a failing test.
And then you just need to extend the import (I guess).

https://github.com/OpenTracksApp/OpenTracks/blob/ecdb5093716dc7fdab5605edc3bf0e3631981d97/src/androidTest/java/de/dennisguse/opentracks/io/file/importer/ExportImportTest.java#L234

Happy coding ;)

**Comment by dennisguse** [comment]
@ronajon your last commit contains some git diff infos. It won't compile.

**Comment by ronajon** [comment]
@dennisguse i'm trying to rebase to main, but got a lot of errors ?
it seems i cannot update my repo now

`ronald@ronald-E402BA:~/StudioProjects/OpenTracks$ git rebase -i main
Successfully rebased and updated refs/heads/main.
ronald@ronald-E402BA:~/StudioProjects/OpenTracks$ git checkout main
Already on 'main'
Your branch is ahead of 'OpenTracksApp/main' by 57 commits.
  (use "git push" to publish your local commits)
ronald@ronald-E402BA:~/StudioProjects/OpenTracks$ `

**Comment by dennisguse** [comment]
Autsch. Remote debugging git is really hard (already locally often sounds like magic).
Depending on the number of changes you have I would recommend just get a fresh branch from main and implement your changes again.
The alternative is to fix all merge conflicts.
But it is also a nice exercise ;)

Or you can get a new branch based upon main and cherrypick the important commits from this branch.

**Comment by ronajon** [comment]
i created a new fork, unfortunately cherrypick the commit did not work, but got the changes by file comparison. 
now i cannot run test "exportimporttest"? it fails with following error
'Installation failed due to: ''cmd package install-create -r -t --full -S 3972759' returns error 'Unknown failure: cmd: Can't find service: package''
Retry'

(working in android studio on linux)

**Comment by dennisguse** [comment]
@ronajon I don't know; does it work in a simulator?

**Comment by ronajon** [comment]
got the latest version of the files
unfortunately i cannot seem to get the test fixed

**Comment by ronajon** [comment]
got my version working again. 
i've looked into the issue for checking heartrate (and cadence and power). 

just found that it's not working for any of the export tests, gpx and kml ?

unfortunately i don't have the knowledge to write new functionality for these tests

**Comment by dennisguse** [comment]
@ronajon Can you push your changes?
Then I can take a look.

**Comment by ronajon** [comment]
> @ronajon Can you push your changes?
> Then I can take a look.

https://github.com/OpenTracksApp/OpenTracks/pull/336

**Comment by dennisguse** [comment]
Follow-up: #337

**Pull request closed without merging**
