### PR TITLE
Database cleanup and optimization

### PR DESCRIPTION
**Pull request by dennisguse**
These changes modify the underlying database structure (via upgrade/downgrade):
* remove unused columns
* add indices.

Testing of schema changes is done on an empty database (without any data).
This includes upgrading from initial database version (23) to most recent (25) as well as downgrade to 23.
Test code will also work for further changes and requiring that database creation as well as upgrade/downgrade lead to identical results.

i did not measure if the performance changed due to adding indices.

### CODE REVIEW

**Comment by dennisguse** [comment]
@pstorch @rgmf This change is rather fundamental.
If you have the time, it would be great if you could test it...

**Comment by pstorch** [comment]
I did a quick test. Looks like it's still working.

In the logcat I see some stacktraces, but if I remember correctly they were already there before:
```

2020-03-16 21:58:32.291 16429-16429/de.dennisguse.opentracks.debug D/StrictMode: StrictMode policy violation; ~duration=34 ms: android.os.strictmode.DiskWriteViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onWriteToDisk(StrictMode.java:1460)
        at android.database.sqlite.SQLiteConnection.applyBlockGuardPolicy(SQLiteConnection.java:1093)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:829)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1564)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1433)
        at de.dennisguse.opentracks.content.provider.CustomContentProvider.insertTrackPoint(CustomContentProvider.java:333)
        at de.dennisguse.opentracks.content.provider.CustomContentProvider.insertContentValues(CustomContentProvider.java:310)
        at de.dennisguse.opentracks.content.provider.CustomContentProvider.insert(CustomContentProvider.java:157)
        at android.content.ContentProvider$Transport.insert(ContentProvider.java:267)
        at android.content.ContentResolver.insert(ContentResolver.java:1588)
 
```

```

2020-03-16 22:01:12.828 16429-16429/de.dennisguse.opentracks.debug D/StrictMode: StrictMode policy violation; ~duration=20 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at android.database.sqlite.SQLiteConnection.applyBlockGuardPolicy(SQLiteConnection.java:1091)
        at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:892)
        at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
        at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
        at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:149)
        at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:137)
        at android.content.ContentResolver.query(ContentResolver.java:822)
        at android.content.ContentResolver.query(ContentResolver.java:753)
        at android.content.ContentResolver.query(ContentResolver.java:711)
        at de.dennisguse.opentracks.android.ContentResolverWrapper.query(ContentResolverWrapper.java:33)
        at de.dennisguse.opentracks.content.provider.ContentProviderUtils.getWaypointCount(ContentProviderUtils.java:546)
        at de.dennisguse.opentracks.TrackListActivity$9.bindView(TrackListActivity.java:293)
        at androidx.cursoradapter.widget.CursorAdapter.getView(CursorAdapter.java:274)
        at android.widget.AbsListView.obtainView(AbsListView.java:2366)

```

**Comment by dennisguse** [comment]
@pstorch Thanks.
The stacktrace occur in debug-builds to show when the rendering is too slow - and give some room for improvement; but so far I did not invest any time into this topic.

**Comment by dennisguse** [comment]
I just removed the commits that were already merged in previous PR.

**Pull request merged**
