### PR TITLE
Marker's list with photos are now loaded efficiently.

### PR DESCRIPTION
**Pull request by rgmf**
**Describe the pull request**
Photos from marker's list are loaded asynchronously and Adapter uses a cache strategy to speed up the loading. It's using 1/8 from free memory (read code).

**Link to the the issue**
#545 

**License agreement**
By opening this pull request, you are providing your contribution under the _Apache License 2.0_ (see [LICENSE.md](LICENSE.md)).

### CODE REVIEW

**Comment by rgmf** [comment]
@dennisguse no hurry, obviously :D

**Comment by dennisguse** [comment]
Looks good.
Did some tiny changes: if you like them please squash and merge; my changes are not worth the commit ><
PS: Could not really test as I don't have too many markers with pictures (lack of test data basically).

**Review by dennisguse — APPROVED** [review]
@rgmf If it works for, then please squash and merge.

**Comment by rgmf** [comment]
> Looks good.
> Did some tiny changes: if you like them please squash and merge; my changes are not worth the commit ><
> PS: Could not really test as I don't have too many markers with pictures (lack of test data basically).

Only a tiny thing:
I've modified the code that calculate the cache to be used. It now is calculated from actual free memory available.

imagen
(source: https://stackoverflow.com/a/18375641)

**Comment by dennisguse** [comment]
Thanks - didnot know that!

**Comment by rgmf** [comment]
I had tested it with about 50 markers with images I have and all work perfectly. But before merge I tested with more than a hundred of markers with images and it crashes if you scroll quickly. That's because the number of thread it creates (I think). So, I have to re-think it: another async strategy for loading images (thread pool?)

Mental note: follow the next algorithm before create a new PR:

```asm
begin:
   test
   jmp begin
```

**Comment by dennisguse** [comment]
All these tiny details :)

Just looking at the code again and there might even be situations in which the multiple threads are started to generate one thumbnail.
Those might try to do the same thing in parallel and whoever finishes last will be in the `LruCache`.
ThreadPool sounds like a good idea and we should check if there is already (ongoing) work in progress for a thumbnail.

One more thing: we could wrap the Thumbnails into a WeakReference before putting them into the LruCache (or even drop the LruCache completely).
In this way the JVM will remove the thumbnails if it needs more RAM - only thing that we should handle a situation were the JVM trashes things and we try to regenerate it.

**Comment by rgmf** [comment]
The bug has been catched... I don't know why but `getContentResolver().openInputStream(..)` cannot called in parallel.

If you call `openInputStream` serveral times in a time then memory usage grow up a lot (according to Android Studio Profiler).

**Comment by dennisguse** [comment]
? I dont understand

**Comment by rgmf** [comment]
> ? I dont understand

Me neither, but it's what is happening... for example, doing scroll more than 40 open input stream are opened and this error is triggered before any of these 40 open input stream were closed.

```
2020-12-16 18:11:02.005 1355-1555/system_process E/InputDispatcher: channel 'c12ac68 de.dennisguse.opentracks.debug/de.dennisguse.opentracks.MarkerListActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
```

Also, with deprecated AsyncTask in `doInBackground` I can see that two input stream are not opened at the same time (like a sempahore was there), and this error is not triggered.

**Comment by dennisguse** [comment]
Can we just usw one thread only?

**Comment by rgmf** [comment]
> Can we just usw one thread only?

Yes, we can. I'll do it that.

**Comment by dennisguse** [comment]
That's actually odd; just by reading the code, there should be at most 10 openinputstreams (one per thread in the executor).
And they should be closed automatically after the image was set. 
Could you check if you can close the inputstream manually?

```
InputStream i;
try {
  i = ....
} finally {
 Log.w(TAG, "inputstream closed");
 if (i != null) i.close();
}
```

And two more things:
1. the executor service must be shutdown the parent object reaches its end of the lifecycle.
2. we still may start multiple thumbnail generations for the same image in parallel (I scroll very fast from the top to the end and back). This might enqueue the same image multiple times and waste a lot of energy.

And one more thing:
What about using a LIFO for the executor service? assuming that the image most recently requested is should be loaded first?
Which actually brings up the next aspect: should be we stop generating thumbnails for images that are not visible anymore?

**Comment by rgmf** [comment]
> That's actually odd; just by reading the code, there should be at most 10 openinputstreams (one per thread in the executor).

Yes, the 40 was with old version, now it opens at most 10 inputstream. But with 10 it also crashes.

> And they should be closed automatically after the image was set.
> Could you check if you can close the inputstream manually?
> 
> ```
> InputStream i;
> try {
>   i = ....
> } finally {
>  Log.w(TAG, "inputstream closed");
>  if (i != null) i.close();
> }
> ```

All inputstreams are closed but before the first inputstream is closed all 10 inputstreams already are opened.

> 
> And two more things:
> 
>     1. the executor service must be shutdown the parent object reaches its end of the lifecycle.

:+1: 

> 
>     2. we still may start multiple thumbnail generations for the same image in parallel (I scroll very fast from the top to the end and back). This might enqueue the same image multiple times and waste a lot of energy.

:+1:  this must be fixed, you are right.

> 
> And one more thing:
> What about using a LIFO for the executor service? assuming that the image most recently requested is should be loaded first?
> Which actually brings up the next aspect: should be we stop generating thumbnails for images that are not visible anymore?

:+1:

**Comment by rgmf** [comment]
@dennisguse only FYI, if you called `openAllPhotos` OT crashes (I think, the code below show what I suspected: opening several inputstreams using the content resolver results in trouble - but no idea why). 

PS/ It's a simple code that I've used to be sure that we cannot open more than X inputstream at the same time.

```java
private String[] photoUrls = new String[] {
            "content://de.dennisguse.opentracks.debug.fileprovider/pictures/Pictures/8/images-24.jpeg",
            "content://de.dennisguse.opentracks.debug.fileprovider/pictures/Pictures/12/images-11.jpeg",
            "content://de.dennisguse.opentracks.debug.fileprovider/pictures/Pictures/31/images-28.jpeg",
            "content://de.dennisguse.opentracks.debug.fileprovider/pictures/Pictures/31/images-29.jpeg",
            "content://de.dennisguse.opentracks.debug.fileprovider/pictures/Pictures/31/images-30.jpeg",
            "content://de.dennisguse.opentracks.debug.fileprovider/pictures/Pictures/33/images-18.jpeg",
            "content://de.dennisguse.opentracks.debug.fileprovider/pictures/Pictures/33/images-19.jpeg",
            "content://de.dennisguse.opentracks.debug.fileprovider/pictures/Pictures/39/images-32.jpeg",
            "content://de.dennisguse.opentracks.debug.fileprovider/pictures/Pictures/70/images-17.jpeg",
            "content://de.dennisguse.opentracks.debug.fileprovider/pictures/Pictures/81/images-8.jpeg",
            "content://de.dennisguse.opentracks.debug.fileprovider/pictures/Pictures/81/images-10.jpeg",
            "content://de.dennisguse.opentracks.debug.fileprovider/pictures/Pictures/98/images-12.jpeg",
            "content://de.dennisguse.opentracks.debug.fileprovider/pictures/Pictures/98/images-13.jpeg",
            "content://de.dennisguse.opentracks.debug.fileprovider/pictures/Pictures/98/images-14.jpeg"
    };

    private void openAllPhotos() {
        for (int i = 0; i < photoUrls.length; i++) {
            asyncOpenPhoto(photoUrls[i]);
        }
    }

    private void asyncOpenPhoto(String photoUrl) {
        executorService.execute(() -> {
            try (InputStream inputStream = activity.getContentResolver().openInputStream(Uri.parse(photoUrl))) {
                Bitmap bitmap = BitmapFactory.decodeStream(inputStream);
            } catch (IOException e) {
                Log.e(TAG, "Failed to image " + e);
            }
        });
    }
```

**Comment by rgmf** [comment]
@dennisguse I CANNOT BELIEVE IT!!!! :angry:

I was using a smartphone and the error is also triggered in the main branch when I enter to Markers. So all the errors I could see in this branch has nothing to do with this branch but with the smartphone (Lineage 16, Sony Xperia).

No problems with any AVD and my current smartphone (Pixel 2 XL). It didn't have any sense.

**Comment by dennisguse** [comment]
That hurts..... real bad.

But one more thing: why do we use the FileProvider at all (I guess the bug is in Android's FileProvider on your device)?
i mean it is our file in our space - so we can access it directly without the need to to the use FileProvider at all.
This alone might improve performance by a lot.
But we store the FileProvider URI in the photoUri column, so it might not be straight forward to convert...

**Comment by rgmf** [comment]
> That hurts..... real bad.
> 
> But one more thing: why do we use the FileProvider at all (I guess the bug is in Android's FileProvider on your device)?
> i mean it is our file in our space - so we can access it directly without the need to to the use FileProvider at all.
> This alone might improve performance by a lot.
> But we store the FileProvider URI in the photoUri column, so it might not be straight forward to convert...

Well... seem that it's not that difficult. We have the name of the file (the last part of the URI) and the trackId... I'll take a look.

**Comment by rgmf** [comment]
- [x] the executor service must be shutdown the parent object reaches its end of the lifecycle.
- [x] we still may start multiple thumbnail generations for the same image in parallel (I scroll very fast from the top to the end and back). This might enqueue the same image multiple times and waste a lot of energy.

**Comment by dennisguse** [comment]
@rgmf About the last point (fileprovider): I guess so, as you already saw a crash on your device and there might be others having trouble with this as well.
From a functional standpoint: this list is not too essential, so if it crashes the application users can still import/export/record stuff.
So, we can also ship it and see what happens and check how many people complain // use GooglePlay reportings.

Should we put this into the upcoming release?

PS: The Marker has the trackId as an attribute.

**Comment by rgmf** [comment]
> @rgmf About the last point (fileprovider): I guess so, as you already saw a crash on your device and there might be others having trouble with this as well.

My faulty device crashes with File / FileInputStream too :(

> From a functional standpoint: this list is not too essential, so if it crashes the application users can still import/export/record stuff.
> So, we can also ship it and see what happens and check how many people complain // use GooglePlay reportings.

I would leave it like it is now.

> Should we put this into the upcoming release?

Yes, I think we can add it to the upcoming release.

With my actual phone it works well with more than 150 images.

**Comment by dennisguse** [comment]
@rgmf Should we include this in v3.15.0?

**Comment by rgmf** [comment]
@dennisguse Yes, we can merge it. It's not as good as Glide is but at least you can move around markers with a lot of photos smoothly :smile: 

I'm going to "press the button"...

**Pull request merged**
